/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service status and build information */
        get: operations["getSystemStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether the first user still has to be created */
        get: operations["getSetupStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create the first admin user and start a session */
        post: operations["completeSetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a session with username and password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current session, user and CSRF token */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List instances (API keys are never returned) */
        get: operations["listInstances"];
        put?: never;
        /** Add a manual instance */
        post: operations["createInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Probe credentials that are not stored yet */
        post: operations["testInstanceInput"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        /** Get one instance */
        get: operations["getInstance"];
        /** Update a manual instance (omit api_key to keep it) */
        put: operations["updateInstance"];
        post?: never;
        /** Delete an instance and everything it owns */
        delete: operations["deleteInstance"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/test": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Probe a stored instance and record the outcome */
        post: operations["testInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/policy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        /** Snatch policy of an instance */
        get: operations["getPolicy"];
        /** Replace the snatch policy of an instance */
        put: operations["updatePolicy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quickie - queue a snatch now (ignores the refractory period) */
        post: operations["triggerRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Clear the history of one instance */
        delete: operations["deleteInstanceEvents"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent snatch runs, newest first */
        get: operations["listRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a queued or leased run */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snatch history, newest first (cursor on before_id) */
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime settings */
        get: operations["getSettings"];
        /** Replace the runtime settings */
        put: operations["updateSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hourly-caps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-instance hourly budget consumption */
        get: operations["getHourlyCaps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/state/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forget processed items (one instance or all) */
        post: operations["resetState"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All schedule windows */
        get: operations["listSchedules"];
        put?: never;
        /** Add a schedule window */
        post: operations["createSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/{scheduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Replace a schedule window */
        put: operations["updateSchedule"];
        post?: never;
        /** Delete a schedule window */
        delete: operations["deleteSchedule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/download-clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List download clients (secrets are never returned) */
        get: operations["listDownloadClients"];
        put?: never;
        /** Add a download client by hand */
        post: operations["createDownloadClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/download-clients/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Observe a download client whose credentials are not stored yet */
        post: operations["testDownloadClientInput"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/download-clients/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest observation of every enabled download client (cached 20 s) */
        get: operations["getDownloadClientStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/download-clients/{clientId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: components["parameters"]["ClientId"];
            };
            cookie?: never;
        };
        /** Get one download client */
        get: operations["getDownloadClient"];
        /** Update a download client (omit secret to keep it) */
        put: operations["updateDownloadClient"];
        post?: never;
        /** Delete a download client */
        delete: operations["deleteDownloadClient"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/download-clients/{clientId}/test": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: components["parameters"]["ClientId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Observe a stored download client now and record the outcome */
        post: operations["testDownloadClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/download-clients/discover": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import the download clients this instance has configured */
        post: operations["discoverDownloadClients"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seerr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Seerr links (API keys are never returned) */
        get: operations["listSeerrLinks"];
        put?: never;
        /** Add a Seerr link */
        post: operations["createSeerrLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seerr/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Probe Seerr credentials that are not stored yet */
        post: operations["testSeerrLinkInput"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seerr/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cached approved-but-unavailable requests with their snatch status */
        get: operations["listSeerrRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seerr/requests/{linkId}/{requestId}/snatch": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                linkId: components["parameters"]["LinkId"];
                requestId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quickie focused on one request (missing snatch of its instance, limited to that movie or series) */
        post: operations["snatchSeerrRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seerr/{linkId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                linkId: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        /** Get one Seerr link */
        get: operations["getSeerrLink"];
        /** Update a Seerr link (omit api_key to keep it) */
        put: operations["updateSeerrLink"];
        post?: never;
        /** Delete a Seerr link and its cached requests */
        delete: operations["deleteSeerrLink"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seerr/{linkId}/test": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                linkId: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Probe a stored Seerr link and record the outcome */
        post: operations["testSeerrLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seerr/{linkId}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                linkId: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh the request cache now (also runs every five minutes) */
        post: operations["syncSeerrLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seerr/{linkId}/import-instances": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                linkId: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create instances from the Sonarr/Radarr servers configured in Seerr */
        post: operations["importSeerrInstances"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cleanuparr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cleanuparr links (API keys are never returned) */
        get: operations["listCleanuparrLinks"];
        put?: never;
        /** Add a Cleanuparr link */
        post: operations["createCleanuparrLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cleanuparr/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Probe Cleanuparr credentials that are not stored yet */
        post: operations["testCleanuparrLinkInput"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cleanuparr/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live view of every enabled Cleanuparr link (cached 30 s) */
        get: operations["getCleanuparrStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cleanuparr/{linkId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                linkId: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        /** Get one Cleanuparr link */
        get: operations["getCleanuparrLink"];
        /** Update a Cleanuparr link (omit api_key to keep it) */
        put: operations["updateCleanuparrLink"];
        post?: never;
        /** Delete a Cleanuparr link */
        delete: operations["deleteCleanuparrLink"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cleanuparr/{linkId}/test": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                linkId: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Probe a stored Cleanuparr link and record the outcome */
        post: operations["testCleanuparrLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/configarr/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import instances from a Configarr config.yml (defaults to the linked files) */
        post: operations["importConfigarr"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/configarr/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Linked-mode state and the last import */
        get: operations["getConfigarrStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /**
             * Format: uri
             * @default about:blank
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            "invalid-params"?: {
                name: string;
                reason: string;
            }[];
        };
        SystemStatus: {
            name: string;
            version: string;
            commit: string;
            build_date: string;
            /** @enum {string} */
            profile: "prod" | "dev";
            setup_complete: boolean;
        };
        SetupStatus: {
            setup_complete: boolean;
        };
        SetupRequest: {
            username: string;
            password: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            username: string;
            /** @enum {string} */
            role: "admin" | "viewer";
        };
        Session: {
            user: components["schemas"]["User"];
            csrf_token: string;
            /** Format: date-time */
            expires_at: string;
        };
        /** @enum {string} */
        AppKind: "sonarr" | "radarr" | "lidarr" | "readarr" | "whisparr_v2" | "whisparr_v3";
        Instance: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["AppKind"];
            name: string;
            /** Format: uri */
            base_url: string;
            enabled: boolean;
            /** @enum {string} */
            source: "manual" | "configarr" | "seerr";
            configarr_key?: string;
            last_seen_version?: string;
            /** Format: date-time */
            last_check_at?: string;
            last_error?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        InstanceInput: {
            kind: components["schemas"]["AppKind"];
            name: string;
            base_url: string;
            api_key: string;
            /** @default true */
            enabled: boolean;
        };
        InstanceUpdate: {
            kind: components["schemas"]["AppKind"];
            name: string;
            base_url: string;
            /** @description Omit or leave empty to keep the stored key */
            api_key?: string;
            /** @default true */
            enabled: boolean;
        };
        ProbeResult: {
            app_name: string;
            version: string;
        };
        SnatchPolicy: {
            /** @description How many missing items one snatch goes after (0 disables missing snatches). */
            missing_per_cycle: number;
            /** @description How many cutoff-unmet items one snatch goes after (0 disables upgrade snatches). */
            upgrade_per_cycle: number;
            /** @description Refractory period: seconds between two snatches of the same kind. */
            cycle_interval_s: number;
            /** @description Stamina: items an instance may search per hour before it needs a rest (1-500). */
            hourly_cap: number;
            /**
             * @description random spreads searches over the library, sequential walks it with a cursor, recent prefers the newest releases with a slice reserved for the backlog
             * @enum {string}
             */
            selection: "random" | "sequential" | "recent";
            monitored_only: boolean;
            skip_future_releases: boolean;
            /** @enum {string} */
            radarr_release_type: "physical" | "digital" | "cinema";
            /** @enum {string} */
            sonarr_missing_mode: "episodes" | "season_packs" | "shows";
            /** @enum {string} */
            sonarr_upgrade_mode: "episodes" | "season_packs";
            /** @enum {string} */
            lidarr_missing_mode: "artist" | "album";
            /** @description Afterglow: hours an item rests after a snatch before it may be touched again. */
            processed_ttl_h: number;
            max_queue_size: number;
            await_command: boolean;
            page_size: number;
            /** @description Skip items the *arr grabbed within this many hours (its history) and items already in its download queue; 0 keeps only the queue check. */
            recent_grab_window_h: number;
            /** @description Afterglow doubles after every fruitless snatch of the same item, up to this many hours. */
            afterglow_max_h: number;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        /** @enum {string} */
        SnatchKind: "missing" | "upgrade";
        RunTrigger: {
            kind: components["schemas"]["SnatchKind"];
        };
        Run: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            instance_id: string;
            kind: components["schemas"]["SnatchKind"];
            /** @enum {string} */
            status: "queued" | "leased" | "done" | "failed" | "cancelled";
            leased_by?: string;
            /** Format: date-time */
            lease_expires_at?: string;
            /** Format: date-time */
            queued_at: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            finished_at?: string;
            searched_count: number;
            error?: string;
            /**
             * Format: int64
             * @description Set for a quickie limited to one movie (Seerr request)
             */
            focus_entity_id?: number;
            /**
             * Format: int64
             * @description Set for a quickie limited to one series (Seerr request)
             */
            focus_group_id?: number;
        };
        Event: {
            /** Format: int64 */
            id: number;
            /** Format: uuid */
            run_id?: string;
            /** Format: uuid */
            instance_id: string;
            /** Format: date-time */
            ts: string;
            /** @enum {string} */
            level: "debug" | "info" | "warn" | "error";
            type: string;
            entity_type?: string;
            /** Format: int64 */
            entity_id?: number;
            title?: string;
            detail?: string;
        };
        CapStatus: {
            /**
             * @description global is the stamina shared by every instance (present only when configured)
             * @enum {string}
             */
            scope: "instance" | "global";
            /**
             * Format: uuid
             * @description Absent for the global entry
             */
            instance_id?: string;
            used: number;
            cap: number;
            /** Format: date-time */
            resets_at: string;
        };
        Settings: {
            history_retention_days: number;
            user_agent: string;
            /** @description Shared stamina across every instance for setups where several *arr apps hit the same indexers (0 = off). */
            global_hourly_cap: number;
            /** Format: date-time */
            updated_at?: string;
        };
        StateReset: {
            /** Format: uuid */
            instance_id?: string;
        };
        StateResetResult: {
            /** Format: int64 */
            forgotten: number;
        };
        ScheduleInput: {
            /**
             * Format: uuid
             * @description Omit for a global window
             */
            instance_id?: string;
            name: string;
            /** @description Weekdays the window applies to (0 = Sunday) */
            days: number[];
            start: string;
            end: string;
            tz: string;
            /** @enum {string} */
            action: "pause" | "cap_override";
            cap_value?: number;
            enabled: boolean;
        };
        Schedule: components["schemas"]["ScheduleInput"] & {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @enum {string} */
        DownloadClientKind: "qbittorrent" | "transmission" | "deluge" | "rtorrent" | "sabnzbd" | "nzbget";
        DownloadClient: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Absent when the client applies to every instance
             */
            instance_id?: string;
            kind: components["schemas"]["DownloadClientKind"];
            /** @enum {string} */
            protocol: "torrent" | "usenet";
            name: string;
            base_url: string;
            username: string;
            enabled: boolean;
            /** @enum {string} */
            source: "manual" | "discovered";
            /** @description Foreplay - defer snatches once this many downloads are active (0 = no limit) */
            max_active: number;
            /**
             * Format: int64
             * @description Foreplay - bytes per second the client may use before snatches are paced (0 = off)
             */
            bandwidth_budget_bps: number;
            /** Format: date-time */
            last_check_at?: string;
            last_error?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        DownloadClientInput: {
            /**
             * Format: uuid
             * @description Pin the client to one instance; omit to apply it to every instance
             */
            instance_id?: string;
            kind: components["schemas"]["DownloadClientKind"];
            name: string;
            base_url: string;
            username?: string;
            /** @description Password, or the API key for SABnzbd. On update, omit to keep the stored one. */
            secret?: string;
            /** @default true */
            enabled: boolean;
            /** @default 0 */
            max_active: number;
            /**
             * Format: int64
             * @default 0
             */
            bandwidth_budget_bps: number;
        };
        DownloadClientStatus: {
            /** Format: uuid */
            client_id?: string;
            name: string;
            kind: components["schemas"]["DownloadClientKind"];
            reachable: boolean;
            paused: boolean;
            active: number;
            queued: number;
            /** Format: int64 */
            download_rate_bps: number;
            /** Format: int64 */
            upload_rate_bps: number;
            version?: string;
            error?: string;
            /** Format: date-time */
            checked_at: string;
        };
        DiscoveryResult: {
            imported: number;
            updated: number;
            removed: number;
            unsupported: string[];
            warnings: string[];
        };
        SeerrLink: {
            /** Format: uuid */
            id: string;
            name: string;
            base_url: string;
            enabled: boolean;
            /**
             * Format: uuid
             * @description Fallback instance for TV requests whose Seerr server cannot be matched by URL
             */
            sonarr_instance_id?: string;
            /**
             * Format: uuid
             * @description Fallback instance for movie requests whose Seerr server cannot be matched by URL
             */
            radarr_instance_id?: string;
            last_seen_version?: string;
            /** Format: date-time */
            last_check_at?: string;
            last_error?: string;
            /** Format: date-time */
            last_sync_at?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        SeerrLinkInput: {
            name: string;
            base_url: string;
            /** @description Required on create; omit on update to keep the stored key */
            api_key?: string;
            /** @default true */
            enabled: boolean;
            /** Format: uuid */
            sonarr_instance_id?: string;
            /** Format: uuid */
            radarr_instance_id?: string;
        };
        SeerrRequest: {
            /** Format: uuid */
            link_id: string;
            link_name: string;
            request_id: number;
            /** @enum {string} */
            media_type: "movie" | "tv";
            tmdb_id: number;
            tvdb_id: number;
            title: string;
            /** @description Seerr MediaRequestStatus: 1 pending, 2 approved, 3 declined, 4 failed, 5 completed */
            request_status: number;
            /** @description Seerr MediaStatus: 1 unknown, 2 pending, 3 processing, 4 partially available, 5 available */
            media_status: number;
            is_4k: boolean;
            requested_by: string;
            seasons: number[];
            /** Format: uuid */
            instance_id?: string;
            instance_name?: string;
            /**
             * Format: int64
             * @description Radarr movie id or Sonarr series id in the resolved instance
             */
            entity_id?: number;
            /** @description True when the request maps to an instance and a library entity and is snatched first */
            resolved: boolean;
            unresolved_reason?: string;
            /** Format: date-time */
            requested_at?: string;
            /** Format: date-time */
            last_snatched_at?: string;
            /** Format: date-time */
            last_seen_at: string;
        };
        SeerrSyncResult: {
            seen: number;
            resolved: number;
            unresolved: number;
            removed: number;
        };
        SeerrImportResult: {
            created: string[];
            skipped: string[];
        };
        CleanuparrLink: {
            /** Format: uuid */
            id: string;
            name: string;
            base_url: string;
            enabled: boolean;
            last_seen_version?: string;
            /** Format: date-time */
            last_check_at?: string;
            last_error?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CleanuparrLinkInput: {
            name: string;
            base_url: string;
            /** @description Required on create; omit on update to keep the stored key */
            api_key?: string;
            /** @default true */
            enabled: boolean;
        };
        CleanuparrStrike: {
            id: string;
            /** @description Stalled, DownloadingMetadata, FailedImport, SlowSpeed, SlowTime or DeadTorrent */
            type: string;
            /** Format: date-time */
            created_at: string;
            /** @description Download client hash or id */
            download_id: string;
            title: string;
            dry_run: boolean;
        };
        CleanuparrStatus: {
            /** Format: uuid */
            link_id: string;
            name: string;
            reachable: boolean;
            error?: string;
            version?: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            checked_at: string;
            /** @description Downloads that currently carry strikes */
            struck_downloads: number;
            marked_for_removal: number;
            removed_downloads: number;
            /** @description Instance count per *arr type as Cleanuparr names them */
            media_managers: {
                [key: string]: number;
            };
            recent_strikes: components["schemas"]["CleanuparrStrike"][];
        };
        ConfigarrImportRequest: {
            /** @description Path to config.yml on the API host; omit to use the linked configuration */
            config_path?: string;
            /** @description Path to secrets.yml; optional */
            secrets_path?: string;
        };
        ConfigarrImportResult: {
            imported: number;
            updated: number;
            /** @description Configarr-owned instances no longer defined, switched off */
            disabled: number;
            warnings: string[];
            /** Format: date-time */
            at: string;
        };
        ConfigarrStatus: {
            /** @description APP_SNATCHARR_CONFIGARR_CONFIG is set */
            linked: boolean;
            config_path?: string;
            secrets_path?: string;
            /** @description The files are polled every 30 s for changes */
            watching: boolean;
            /** Format: date-time */
            last_import_at?: string;
            last_result?: components["schemas"]["ConfigarrImportResult"];
            last_error?: string;
        };
    };
    responses: {
        /** @description RFC 9457 problem details */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        InstanceId: string;
        ClientId: string;
        LinkId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSystemStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getSetupStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Setup status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    completeSetup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description User created and session started */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Session started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session ended */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session */
            200: {
                headers: {
                    /** @description Token to echo on unsafe requests */
                    "X-CSRF-Token"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listInstances: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instances */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instance"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstanceInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instance"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    testInstanceInput: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstanceInput"];
            };
        };
        responses: {
            /** @description Probe result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instance"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstanceUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instance"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    testInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Probe result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnatchPolicy"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updatePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnatchPolicy"];
            };
        };
        responses: {
            /** @description Policy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnatchPolicy"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    triggerRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunTrigger"];
            };
        };
        responses: {
            /** @description A run for this kind is already queued or leased */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Run queued */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteInstanceEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listRuns: {
        parameters: {
            query?: {
                instance_id?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listEvents: {
        parameters: {
            query?: {
                instance_id?: string;
                before_id?: number;
                type?: string;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Settings"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getHourlyCaps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Caps */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapStatus"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    resetState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StateReset"];
            };
        };
        responses: {
            /** @description Rows forgotten */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateResetResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listSchedules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schedules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listDownloadClients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Download clients */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadClient"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createDownloadClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DownloadClientInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadClient"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    testDownloadClientInput: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DownloadClientInput"];
            };
        };
        responses: {
            /** @description Observation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadClientStatus"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getDownloadClientStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Observations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadClientStatus"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getDownloadClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: components["parameters"]["ClientId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Download client */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadClient"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateDownloadClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: components["parameters"]["ClientId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DownloadClientInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadClient"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteDownloadClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: components["parameters"]["ClientId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    testDownloadClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: components["parameters"]["ClientId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Observation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadClientStatus"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    discoverDownloadClients: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Discovery result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listSeerrLinks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Links */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeerrLink"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createSeerrLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeerrLinkInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeerrLink"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    testSeerrLinkInput: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeerrLinkInput"];
            };
        };
        responses: {
            /** @description Probe result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listSeerrRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeerrRequest"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    snatchSeerrRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                linkId: components["parameters"]["LinkId"];
                requestId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queued */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getSeerrLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                linkId: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Link */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeerrLink"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateSeerrLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                linkId: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeerrLinkInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeerrLink"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteSeerrLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                linkId: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    testSeerrLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                linkId: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Probe result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    syncSeerrLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                linkId: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sync result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeerrSyncResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    importSeerrInstances: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                linkId: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Import result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeerrImportResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listCleanuparrLinks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Links */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanuparrLink"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createCleanuparrLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CleanuparrLinkInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanuparrLink"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    testCleanuparrLinkInput: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CleanuparrLinkInput"];
            };
        };
        responses: {
            /** @description Probe result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getCleanuparrStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status per link */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanuparrStatus"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getCleanuparrLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                linkId: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Link */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanuparrLink"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateCleanuparrLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                linkId: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CleanuparrLinkInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanuparrLink"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteCleanuparrLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                linkId: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    testCleanuparrLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                linkId: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Probe result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    importConfigarr: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ConfigarrImportRequest"];
            };
        };
        responses: {
            /** @description Import result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigarrImportResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getConfigarrStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigarrStatus"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
