// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one

SELECT count(*) FROM users
`

// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
// SPDX-License-Identifier: EUPL-1.2
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, password_hash, role, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $5)
RETURNING id, username, password_hash, role, created_at, updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	Role         string
	CreatedAt    time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, owner_id, scopes, hash, created_at, expires_at, revoked_at FROM api_keys WHERE id = $1
`

func (q *Queries) GetAPIKey(ctx context.Context, id string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Scopes,
		&i.Hash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, password_hash, role, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, role, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIKeysByOwner = `-- name: ListAPIKeysByOwner :many
SELECT id, owner_id, scopes, hash, created_at, expires_at, revoked_at FROM api_keys WHERE owner_id = $1 AND revoked_at IS NULL ORDER BY created_at
`

func (q *Queries) ListAPIKeysByOwner(ctx context.Context, ownerID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Scopes,
			&i.Hash,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, role, created_at, updated_at FROM users ORDER BY username
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadSession = `-- name: LoadSession :one
SELECT data FROM sessions WHERE id = $1 AND expires_at > $2
`

type LoadSessionParams struct {
	ID        string
	ExpiresAt time.Time
}

func (q *Queries) LoadSession(ctx context.Context, arg LoadSessionParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, loadSession, arg.ID, arg.ExpiresAt)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const purgeExpiredSessions = `-- name: PurgeExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= $1
`

func (q *Queries) PurgeExpiredSessions(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys SET revoked_at = $2 WHERE id = $1 AND revoked_at IS NULL
`

type RevokeAPIKeyParams struct {
	ID        string
	RevokedAt *time.Time
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveAPIKey = `-- name: SaveAPIKey :exec
INSERT INTO api_keys (id, owner_id, scopes, hash, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type SaveAPIKeyParams struct {
	ID        string
	OwnerID   uuid.UUID
	Scopes    []string
	Hash      []byte
	CreatedAt time.Time
	ExpiresAt *time.Time
}

func (q *Queries) SaveAPIKey(ctx context.Context, arg SaveAPIKeyParams) error {
	_, err := q.db.Exec(ctx, saveAPIKey,
		arg.ID,
		arg.OwnerID,
		arg.Scopes,
		arg.Hash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const saveSession = `-- name: SaveSession :exec
INSERT INTO sessions (id, data, expires_at) VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET data = EXCLUDED.data, expires_at = EXCLUDED.expires_at
`

type SaveSessionParams struct {
	ID        string
	Data      []byte
	ExpiresAt time.Time
}

func (q *Queries) SaveSession(ctx context.Context, arg SaveSessionParams) error {
	_, err := q.db.Exec(ctx, saveSession, arg.ID, arg.Data, arg.ExpiresAt)
	return err
}
