// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cleanuparr.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCleanuparrLink = `-- name: CreateCleanuparrLink :one

INSERT INTO cleanuparr_links (id, name, base_url, api_key_enc, enabled, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $6)
RETURNING id, name, base_url, api_key_enc, enabled, last_seen_version, last_check_at, last_error, created_at, updated_at
`

type CreateCleanuparrLinkParams struct {
	ID        uuid.UUID
	Name      string
	BaseUrl   string
	ApiKeyEnc []byte
	Enabled   bool
	CreatedAt time.Time
}

// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
// SPDX-License-Identifier: EUPL-1.2
func (q *Queries) CreateCleanuparrLink(ctx context.Context, arg CreateCleanuparrLinkParams) (CleanuparrLink, error) {
	row := q.db.QueryRow(ctx, createCleanuparrLink,
		arg.ID,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKeyEnc,
		arg.Enabled,
		arg.CreatedAt,
	)
	var i CleanuparrLink
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyEnc,
		&i.Enabled,
		&i.LastSeenVersion,
		&i.LastCheckAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCleanuparrLink = `-- name: DeleteCleanuparrLink :execrows
DELETE FROM cleanuparr_links WHERE id = $1
`

func (q *Queries) DeleteCleanuparrLink(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCleanuparrLink, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCleanuparrLink = `-- name: GetCleanuparrLink :one
SELECT id, name, base_url, api_key_enc, enabled, last_seen_version, last_check_at, last_error, created_at, updated_at FROM cleanuparr_links WHERE id = $1
`

func (q *Queries) GetCleanuparrLink(ctx context.Context, id uuid.UUID) (CleanuparrLink, error) {
	row := q.db.QueryRow(ctx, getCleanuparrLink, id)
	var i CleanuparrLink
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyEnc,
		&i.Enabled,
		&i.LastSeenVersion,
		&i.LastCheckAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCleanuparrLinks = `-- name: ListCleanuparrLinks :many
SELECT id, name, base_url, api_key_enc, enabled, last_seen_version, last_check_at, last_error, created_at, updated_at FROM cleanuparr_links ORDER BY name
`

func (q *Queries) ListCleanuparrLinks(ctx context.Context) ([]CleanuparrLink, error) {
	rows, err := q.db.Query(ctx, listCleanuparrLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CleanuparrLink{}
	for rows.Next() {
		var i CleanuparrLink
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.ApiKeyEnc,
			&i.Enabled,
			&i.LastSeenVersion,
			&i.LastCheckAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledCleanuparrLinks = `-- name: ListEnabledCleanuparrLinks :many
SELECT id, name, base_url, api_key_enc, enabled, last_seen_version, last_check_at, last_error, created_at, updated_at FROM cleanuparr_links WHERE enabled ORDER BY name
`

func (q *Queries) ListEnabledCleanuparrLinks(ctx context.Context) ([]CleanuparrLink, error) {
	rows, err := q.db.Query(ctx, listEnabledCleanuparrLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CleanuparrLink{}
	for rows.Next() {
		var i CleanuparrLink
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.ApiKeyEnc,
			&i.Enabled,
			&i.LastSeenVersion,
			&i.LastCheckAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordCleanuparrCheck = `-- name: RecordCleanuparrCheck :exec
UPDATE cleanuparr_links
SET last_seen_version = $2, last_check_at = $3, last_error = $4, updated_at = $3
WHERE id = $1
`

type RecordCleanuparrCheckParams struct {
	ID              uuid.UUID
	LastSeenVersion *string
	LastCheckAt     *time.Time
	LastError       *string
}

func (q *Queries) RecordCleanuparrCheck(ctx context.Context, arg RecordCleanuparrCheckParams) error {
	_, err := q.db.Exec(ctx, recordCleanuparrCheck,
		arg.ID,
		arg.LastSeenVersion,
		arg.LastCheckAt,
		arg.LastError,
	)
	return err
}

const updateCleanuparrLink = `-- name: UpdateCleanuparrLink :one
UPDATE cleanuparr_links
SET name = $2, base_url = $3, api_key_enc = $4, enabled = $5, updated_at = $6
WHERE id = $1
RETURNING id, name, base_url, api_key_enc, enabled, last_seen_version, last_check_at, last_error, created_at, updated_at
`

type UpdateCleanuparrLinkParams struct {
	ID        uuid.UUID
	Name      string
	BaseUrl   string
	ApiKeyEnc []byte
	Enabled   bool
	UpdatedAt time.Time
}

func (q *Queries) UpdateCleanuparrLink(ctx context.Context, arg UpdateCleanuparrLinkParams) (CleanuparrLink, error) {
	row := q.db.QueryRow(ctx, updateCleanuparrLink,
		arg.ID,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKeyEnc,
		arg.Enabled,
		arg.UpdatedAt,
	)
	var i CleanuparrLink
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyEnc,
		&i.Enabled,
		&i.LastSeenVersion,
		&i.LastCheckAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
