// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: download_clients.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDownloadClient = `-- name: CreateDownloadClient :one

INSERT INTO download_clients (
    id, instance_id, kind, name, base_url, username, secret_enc, enabled, source, remote_id,
    max_active, bandwidth_budget_bps, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $13
)
RETURNING id, instance_id, kind, name, base_url, username, secret_enc, enabled, source, remote_id, max_active, bandwidth_budget_bps, last_check_at, last_error, created_at, updated_at
`

type CreateDownloadClientParams struct {
	ID                 uuid.UUID
	InstanceID         *uuid.UUID
	Kind               string
	Name               string
	BaseUrl            string
	Username           string
	SecretEnc          []byte
	Enabled            bool
	Source             string
	RemoteID           *int32
	MaxActive          int32
	BandwidthBudgetBps int64
	CreatedAt          time.Time
}

// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
// SPDX-License-Identifier: EUPL-1.2
func (q *Queries) CreateDownloadClient(ctx context.Context, arg CreateDownloadClientParams) (DownloadClient, error) {
	row := q.db.QueryRow(ctx, createDownloadClient,
		arg.ID,
		arg.InstanceID,
		arg.Kind,
		arg.Name,
		arg.BaseUrl,
		arg.Username,
		arg.SecretEnc,
		arg.Enabled,
		arg.Source,
		arg.RemoteID,
		arg.MaxActive,
		arg.BandwidthBudgetBps,
		arg.CreatedAt,
	)
	var i DownloadClient
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Kind,
		&i.Name,
		&i.BaseUrl,
		&i.Username,
		&i.SecretEnc,
		&i.Enabled,
		&i.Source,
		&i.RemoteID,
		&i.MaxActive,
		&i.BandwidthBudgetBps,
		&i.LastCheckAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDownloadClient = `-- name: DeleteDownloadClient :execrows
DELETE FROM download_clients WHERE id = $1
`

func (q *Queries) DeleteDownloadClient(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDownloadClient, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleDiscoveredDownloadClients = `-- name: DeleteStaleDiscoveredDownloadClients :execrows
DELETE FROM download_clients
WHERE instance_id = $1 AND source = 'discovered' AND remote_id IS NOT NULL
  AND NOT (remote_id = ANY($2::int[]))
`

type DeleteStaleDiscoveredDownloadClientsParams struct {
	InstanceID    *uuid.UUID
	KeepRemoteIds []int32
}

func (q *Queries) DeleteStaleDiscoveredDownloadClients(ctx context.Context, arg DeleteStaleDiscoveredDownloadClientsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleDiscoveredDownloadClients, arg.InstanceID, arg.KeepRemoteIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDownloadClient = `-- name: GetDownloadClient :one
SELECT id, instance_id, kind, name, base_url, username, secret_enc, enabled, source, remote_id, max_active, bandwidth_budget_bps, last_check_at, last_error, created_at, updated_at FROM download_clients WHERE id = $1
`

func (q *Queries) GetDownloadClient(ctx context.Context, id uuid.UUID) (DownloadClient, error) {
	row := q.db.QueryRow(ctx, getDownloadClient, id)
	var i DownloadClient
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Kind,
		&i.Name,
		&i.BaseUrl,
		&i.Username,
		&i.SecretEnc,
		&i.Enabled,
		&i.Source,
		&i.RemoteID,
		&i.MaxActive,
		&i.BandwidthBudgetBps,
		&i.LastCheckAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDownloadClients = `-- name: ListDownloadClients :many
SELECT id, instance_id, kind, name, base_url, username, secret_enc, enabled, source, remote_id, max_active, bandwidth_budget_bps, last_check_at, last_error, created_at, updated_at FROM download_clients ORDER BY name, created_at
`

func (q *Queries) ListDownloadClients(ctx context.Context) ([]DownloadClient, error) {
	rows, err := q.db.Query(ctx, listDownloadClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownloadClient{}
	for rows.Next() {
		var i DownloadClient
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Kind,
			&i.Name,
			&i.BaseUrl,
			&i.Username,
			&i.SecretEnc,
			&i.Enabled,
			&i.Source,
			&i.RemoteID,
			&i.MaxActive,
			&i.BandwidthBudgetBps,
			&i.LastCheckAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDownloadClientsForInstance = `-- name: ListDownloadClientsForInstance :many
SELECT id, instance_id, kind, name, base_url, username, secret_enc, enabled, source, remote_id, max_active, bandwidth_budget_bps, last_check_at, last_error, created_at, updated_at FROM download_clients
WHERE enabled AND (instance_id IS NULL OR instance_id = $1)
ORDER BY name, created_at
`

func (q *Queries) ListDownloadClientsForInstance(ctx context.Context, instanceID *uuid.UUID) ([]DownloadClient, error) {
	rows, err := q.db.Query(ctx, listDownloadClientsForInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownloadClient{}
	for rows.Next() {
		var i DownloadClient
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Kind,
			&i.Name,
			&i.BaseUrl,
			&i.Username,
			&i.SecretEnc,
			&i.Enabled,
			&i.Source,
			&i.RemoteID,
			&i.MaxActive,
			&i.BandwidthBudgetBps,
			&i.LastCheckAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledDownloadClients = `-- name: ListEnabledDownloadClients :many
SELECT id, instance_id, kind, name, base_url, username, secret_enc, enabled, source, remote_id, max_active, bandwidth_budget_bps, last_check_at, last_error, created_at, updated_at FROM download_clients WHERE enabled ORDER BY name, created_at
`

func (q *Queries) ListEnabledDownloadClients(ctx context.Context) ([]DownloadClient, error) {
	rows, err := q.db.Query(ctx, listEnabledDownloadClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownloadClient{}
	for rows.Next() {
		var i DownloadClient
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Kind,
			&i.Name,
			&i.BaseUrl,
			&i.Username,
			&i.SecretEnc,
			&i.Enabled,
			&i.Source,
			&i.RemoteID,
			&i.MaxActive,
			&i.BandwidthBudgetBps,
			&i.LastCheckAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDownloadClientCheck = `-- name: RecordDownloadClientCheck :exec
UPDATE download_clients
SET last_check_at = $2, last_error = $3, updated_at = $2
WHERE id = $1
`

type RecordDownloadClientCheckParams struct {
	ID          uuid.UUID
	LastCheckAt *time.Time
	LastError   *string
}

func (q *Queries) RecordDownloadClientCheck(ctx context.Context, arg RecordDownloadClientCheckParams) error {
	_, err := q.db.Exec(ctx, recordDownloadClientCheck, arg.ID, arg.LastCheckAt, arg.LastError)
	return err
}

const updateDownloadClient = `-- name: UpdateDownloadClient :one
UPDATE download_clients
SET instance_id = $2, kind = $3, name = $4, base_url = $5, username = $6, secret_enc = $7,
    enabled = $8, max_active = $9, bandwidth_budget_bps = $10, updated_at = $11
WHERE id = $1
RETURNING id, instance_id, kind, name, base_url, username, secret_enc, enabled, source, remote_id, max_active, bandwidth_budget_bps, last_check_at, last_error, created_at, updated_at
`

type UpdateDownloadClientParams struct {
	ID                 uuid.UUID
	InstanceID         *uuid.UUID
	Kind               string
	Name               string
	BaseUrl            string
	Username           string
	SecretEnc          []byte
	Enabled            bool
	MaxActive          int32
	BandwidthBudgetBps int64
	UpdatedAt          time.Time
}

func (q *Queries) UpdateDownloadClient(ctx context.Context, arg UpdateDownloadClientParams) (DownloadClient, error) {
	row := q.db.QueryRow(ctx, updateDownloadClient,
		arg.ID,
		arg.InstanceID,
		arg.Kind,
		arg.Name,
		arg.BaseUrl,
		arg.Username,
		arg.SecretEnc,
		arg.Enabled,
		arg.MaxActive,
		arg.BandwidthBudgetBps,
		arg.UpdatedAt,
	)
	var i DownloadClient
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Kind,
		&i.Name,
		&i.BaseUrl,
		&i.Username,
		&i.SecretEnc,
		&i.Enabled,
		&i.Source,
		&i.RemoteID,
		&i.MaxActive,
		&i.BandwidthBudgetBps,
		&i.LastCheckAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDiscoveredDownloadClient = `-- name: UpsertDiscoveredDownloadClient :one
INSERT INTO download_clients (
    id, instance_id, kind, name, base_url, username, secret_enc, enabled, source, remote_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, 'discovered', $9, $10, $10
)
ON CONFLICT (instance_id, remote_id) WHERE remote_id IS NOT NULL DO UPDATE
SET kind = EXCLUDED.kind, name = EXCLUDED.name, base_url = EXCLUDED.base_url, username = EXCLUDED.username,
    secret_enc = EXCLUDED.secret_enc, enabled = EXCLUDED.enabled, updated_at = EXCLUDED.updated_at
RETURNING id, instance_id, kind, name, base_url, username, secret_enc, enabled, source, remote_id, max_active, bandwidth_budget_bps, last_check_at, last_error, created_at, updated_at, (xmax = 0) AS inserted
`

type UpsertDiscoveredDownloadClientParams struct {
	ID         uuid.UUID
	InstanceID *uuid.UUID
	Kind       string
	Name       string
	BaseUrl    string
	Username   string
	SecretEnc  []byte
	Enabled    bool
	RemoteID   *int32
	CreatedAt  time.Time
}

type UpsertDiscoveredDownloadClientRow struct {
	ID                 uuid.UUID
	InstanceID         *uuid.UUID
	Kind               string
	Name               string
	BaseUrl            string
	Username           string
	SecretEnc          []byte
	Enabled            bool
	Source             string
	RemoteID           *int32
	MaxActive          int32
	BandwidthBudgetBps int64
	LastCheckAt        *time.Time
	LastError          *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Inserted           bool
}

func (q *Queries) UpsertDiscoveredDownloadClient(ctx context.Context, arg UpsertDiscoveredDownloadClientParams) (UpsertDiscoveredDownloadClientRow, error) {
	row := q.db.QueryRow(ctx, upsertDiscoveredDownloadClient,
		arg.ID,
		arg.InstanceID,
		arg.Kind,
		arg.Name,
		arg.BaseUrl,
		arg.Username,
		arg.SecretEnc,
		arg.Enabled,
		arg.RemoteID,
		arg.CreatedAt,
	)
	var i UpsertDiscoveredDownloadClientRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Kind,
		&i.Name,
		&i.BaseUrl,
		&i.Username,
		&i.SecretEnc,
		&i.Enabled,
		&i.Source,
		&i.RemoteID,
		&i.MaxActive,
		&i.BandwidthBudgetBps,
		&i.LastCheckAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Inserted,
	)
	return i, err
}
