// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteEventsForInstance = `-- name: DeleteEventsForInstance :execrows
DELETE FROM hunt_events WHERE instance_id = $1
`

func (q *Queries) DeleteEventsForInstance(ctx context.Context, instanceID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEventsForInstance, instanceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertEvent = `-- name: InsertEvent :one

INSERT INTO hunt_events (run_id, instance_id, ts, level, type, entity_type, entity_id, title, detail)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type InsertEventParams struct {
	RunID      *uuid.UUID
	InstanceID uuid.UUID
	Ts         time.Time
	Level      string
	Type       string
	EntityType string
	EntityID   int64
	Title      string
	Detail     string
}

// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
// SPDX-License-Identifier: EUPL-1.2
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.RunID,
		arg.InstanceID,
		arg.Ts,
		arg.Level,
		arg.Type,
		arg.EntityType,
		arg.EntityID,
		arg.Title,
		arg.Detail,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, run_id, instance_id, ts, level, type, entity_type, entity_id, title, detail FROM hunt_events
WHERE ($1::uuid IS NULL OR instance_id = $1::uuid)
  AND ($2::bigint IS NULL OR id < $2::bigint)
  AND ($3::text IS NULL OR type = $3::text)
ORDER BY id DESC
LIMIT $4
`

type ListEventsParams struct {
	InstanceID *uuid.UUID
	BeforeID   *int64
	Type       *string
	PageSize   int32
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]HuntEvent, error) {
	rows, err := q.db.Query(ctx, listEvents,
		arg.InstanceID,
		arg.BeforeID,
		arg.Type,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HuntEvent{}
	for rows.Next() {
		var i HuntEvent
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.InstanceID,
			&i.Ts,
			&i.Level,
			&i.Type,
			&i.EntityType,
			&i.EntityID,
			&i.Title,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeEventsBefore = `-- name: PurgeEventsBefore :execrows
DELETE FROM hunt_events WHERE ts < $1
`

func (q *Queries) PurgeEventsBefore(ctx context.Context, ts time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeEventsBefore, ts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
