// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: instances.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countInstancesByBaseURL = `-- name: CountInstancesByBaseURL :one
SELECT count(*) FROM instances WHERE lower(base_url) = lower($1) AND id <> $2
`

type CountInstancesByBaseURLParams struct {
	Lower string
	ID    uuid.UUID
}

func (q *Queries) CountInstancesByBaseURL(ctx context.Context, arg CountInstancesByBaseURLParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInstancesByBaseURL, arg.Lower, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInstancesByBaseURLAndNotSource = `-- name: CountInstancesByBaseURLAndNotSource :one
SELECT count(*) FROM instances WHERE lower(base_url) = lower($1) AND source <> $2
`

type CountInstancesByBaseURLAndNotSourceParams struct {
	Lower  string
	Source string
}

func (q *Queries) CountInstancesByBaseURLAndNotSource(ctx context.Context, arg CountInstancesByBaseURLAndNotSourceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInstancesByBaseURLAndNotSource, arg.Lower, arg.Source)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInstance = `-- name: CreateInstance :one

INSERT INTO instances (id, kind, name, base_url, api_key_enc, enabled, source, configarr_key, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $9)
RETURNING id, kind, name, base_url, api_key_enc, enabled, source, configarr_key, last_seen_version, last_check_at, last_error, created_at, updated_at
`

type CreateInstanceParams struct {
	ID           uuid.UUID
	Kind         string
	Name         string
	BaseUrl      string
	ApiKeyEnc    []byte
	Enabled      bool
	Source       string
	ConfigarrKey *string
	CreatedAt    time.Time
}

// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
// SPDX-License-Identifier: EUPL-1.2
func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) (Instance, error) {
	row := q.db.QueryRow(ctx, createInstance,
		arg.ID,
		arg.Kind,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKeyEnc,
		arg.Enabled,
		arg.Source,
		arg.ConfigarrKey,
		arg.CreatedAt,
	)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyEnc,
		&i.Enabled,
		&i.Source,
		&i.ConfigarrKey,
		&i.LastSeenVersion,
		&i.LastCheckAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInstance = `-- name: DeleteInstance :execrows
DELETE FROM instances WHERE id = $1
`

func (q *Queries) DeleteInstance(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInstance, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableConfigarrInstancesNotIn = `-- name: DisableConfigarrInstancesNotIn :execrows
UPDATE instances
SET enabled = FALSE, last_error = 'removed from the Configarr configuration', updated_at = $1
WHERE source = 'configarr' AND enabled AND NOT (configarr_key = ANY($2::text[]))
`

type DisableConfigarrInstancesNotInParams struct {
	UpdatedAt time.Time
	KeepKeys  []string
}

func (q *Queries) DisableConfigarrInstancesNotIn(ctx context.Context, arg DisableConfigarrInstancesNotInParams) (int64, error) {
	result, err := q.db.Exec(ctx, disableConfigarrInstancesNotIn, arg.UpdatedAt, arg.KeepKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInstance = `-- name: GetInstance :one
SELECT id, kind, name, base_url, api_key_enc, enabled, source, configarr_key, last_seen_version, last_check_at, last_error, created_at, updated_at FROM instances WHERE id = $1
`

func (q *Queries) GetInstance(ctx context.Context, id uuid.UUID) (Instance, error) {
	row := q.db.QueryRow(ctx, getInstance, id)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyEnc,
		&i.Enabled,
		&i.Source,
		&i.ConfigarrKey,
		&i.LastSeenVersion,
		&i.LastCheckAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstanceByConfigarrKey = `-- name: GetInstanceByConfigarrKey :one
SELECT id, kind, name, base_url, api_key_enc, enabled, source, configarr_key, last_seen_version, last_check_at, last_error, created_at, updated_at FROM instances WHERE configarr_key = $1
`

func (q *Queries) GetInstanceByConfigarrKey(ctx context.Context, configarrKey *string) (Instance, error) {
	row := q.db.QueryRow(ctx, getInstanceByConfigarrKey, configarrKey)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyEnc,
		&i.Enabled,
		&i.Source,
		&i.ConfigarrKey,
		&i.LastSeenVersion,
		&i.LastCheckAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledInstances = `-- name: ListEnabledInstances :many
SELECT id, kind, name, base_url, api_key_enc, enabled, source, configarr_key, last_seen_version, last_check_at, last_error, created_at, updated_at FROM instances WHERE enabled ORDER BY kind, name
`

func (q *Queries) ListEnabledInstances(ctx context.Context) ([]Instance, error) {
	rows, err := q.db.Query(ctx, listEnabledInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Instance{}
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.BaseUrl,
			&i.ApiKeyEnc,
			&i.Enabled,
			&i.Source,
			&i.ConfigarrKey,
			&i.LastSeenVersion,
			&i.LastCheckAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstances = `-- name: ListInstances :many
SELECT id, kind, name, base_url, api_key_enc, enabled, source, configarr_key, last_seen_version, last_check_at, last_error, created_at, updated_at FROM instances ORDER BY kind, name
`

func (q *Queries) ListInstances(ctx context.Context) ([]Instance, error) {
	rows, err := q.db.Query(ctx, listInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Instance{}
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.BaseUrl,
			&i.ApiKeyEnc,
			&i.Enabled,
			&i.Source,
			&i.ConfigarrKey,
			&i.LastSeenVersion,
			&i.LastCheckAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordInstanceCheck = `-- name: RecordInstanceCheck :exec
UPDATE instances
SET last_seen_version = $2, last_check_at = $3, last_error = $4, updated_at = $3
WHERE id = $1
`

type RecordInstanceCheckParams struct {
	ID              uuid.UUID
	LastSeenVersion *string
	LastCheckAt     *time.Time
	LastError       *string
}

func (q *Queries) RecordInstanceCheck(ctx context.Context, arg RecordInstanceCheckParams) error {
	_, err := q.db.Exec(ctx, recordInstanceCheck,
		arg.ID,
		arg.LastSeenVersion,
		arg.LastCheckAt,
		arg.LastError,
	)
	return err
}

const updateInstance = `-- name: UpdateInstance :one
UPDATE instances
SET kind = $2, name = $3, base_url = $4, api_key_enc = $5, enabled = $6, updated_at = $7
WHERE id = $1
RETURNING id, kind, name, base_url, api_key_enc, enabled, source, configarr_key, last_seen_version, last_check_at, last_error, created_at, updated_at
`

type UpdateInstanceParams struct {
	ID        uuid.UUID
	Kind      string
	Name      string
	BaseUrl   string
	ApiKeyEnc []byte
	Enabled   bool
	UpdatedAt time.Time
}

func (q *Queries) UpdateInstance(ctx context.Context, arg UpdateInstanceParams) (Instance, error) {
	row := q.db.QueryRow(ctx, updateInstance,
		arg.ID,
		arg.Kind,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKeyEnc,
		arg.Enabled,
		arg.UpdatedAt,
	)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyEnc,
		&i.Enabled,
		&i.Source,
		&i.ConfigarrKey,
		&i.LastSeenVersion,
		&i.LastCheckAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertConfigarrInstance = `-- name: UpsertConfigarrInstance :one
INSERT INTO instances (id, kind, name, base_url, api_key_enc, enabled, source, configarr_key, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, 'configarr', $7, $8, $8)
ON CONFLICT (configarr_key) DO UPDATE
SET kind = EXCLUDED.kind, name = EXCLUDED.name, base_url = EXCLUDED.base_url,
    api_key_enc = EXCLUDED.api_key_enc, enabled = EXCLUDED.enabled, updated_at = EXCLUDED.updated_at
RETURNING id, kind, name, base_url, api_key_enc, enabled, source, configarr_key, last_seen_version, last_check_at, last_error, created_at, updated_at, (xmax = 0) AS inserted
`

type UpsertConfigarrInstanceParams struct {
	ID           uuid.UUID
	Kind         string
	Name         string
	BaseUrl      string
	ApiKeyEnc    []byte
	Enabled      bool
	ConfigarrKey *string
	CreatedAt    time.Time
}

type UpsertConfigarrInstanceRow struct {
	ID              uuid.UUID
	Kind            string
	Name            string
	BaseUrl         string
	ApiKeyEnc       []byte
	Enabled         bool
	Source          string
	ConfigarrKey    *string
	LastSeenVersion *string
	LastCheckAt     *time.Time
	LastError       *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Inserted        bool
}

func (q *Queries) UpsertConfigarrInstance(ctx context.Context, arg UpsertConfigarrInstanceParams) (UpsertConfigarrInstanceRow, error) {
	row := q.db.QueryRow(ctx, upsertConfigarrInstance,
		arg.ID,
		arg.Kind,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKeyEnc,
		arg.Enabled,
		arg.ConfigarrKey,
		arg.CreatedAt,
	)
	var i UpsertConfigarrInstanceRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyEnc,
		&i.Enabled,
		&i.Source,
		&i.ConfigarrKey,
		&i.LastSeenVersion,
		&i.LastCheckAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Inserted,
	)
	return i, err
}
