// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memory.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countProcessed = `-- name: CountProcessed :one
SELECT count(*) FROM processed_items WHERE instance_id = $1 AND expires_at > $2
`

type CountProcessedParams struct {
	InstanceID uuid.UUID
	ExpiresAt  time.Time
}

func (q *Queries) CountProcessed(ctx context.Context, arg CountProcessedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProcessed, arg.InstanceID, arg.ExpiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const ensureBucket = `-- name: EnsureBucket :exec
INSERT INTO rate_buckets (instance_id, window_start, used) VALUES ($1, $2, 0)
ON CONFLICT (instance_id, window_start) DO NOTHING
`

type EnsureBucketParams struct {
	InstanceID  uuid.UUID
	WindowStart time.Time
}

func (q *Queries) EnsureBucket(ctx context.Context, arg EnsureBucketParams) error {
	_, err := q.db.Exec(ctx, ensureBucket, arg.InstanceID, arg.WindowStart)
	return err
}

const filterUnprocessed = `-- name: FilterUnprocessed :many

SELECT c.id::bigint AS entity_id
FROM unnest($1::bigint[]) AS c(id)
WHERE NOT EXISTS (
    SELECT 1 FROM processed_items p
    WHERE p.instance_id = $2
      AND p.kind = $3
      AND p.entity_type = $4
      AND p.entity_id = c.id
      AND p.expires_at > $5
)
`

type FilterUnprocessedParams struct {
	EntityIds  []int64
	InstanceID uuid.UUID
	Kind       string
	EntityType string
	Now        time.Time
}

// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
// SPDX-License-Identifier: EUPL-1.2
func (q *Queries) FilterUnprocessed(ctx context.Context, arg FilterUnprocessedParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, filterUnprocessed,
		arg.EntityIds,
		arg.InstanceID,
		arg.Kind,
		arg.EntityType,
		arg.Now,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var entity_id int64
		if err := rows.Scan(&entity_id); err != nil {
			return nil, err
		}
		items = append(items, entity_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBucketUsed = `-- name: GetBucketUsed :one
SELECT COALESCE((SELECT used FROM rate_buckets WHERE instance_id = $1 AND window_start = $2), 0)::int AS used
`

type GetBucketUsedParams struct {
	InstanceID  uuid.UUID
	WindowStart time.Time
}

func (q *Queries) GetBucketUsed(ctx context.Context, arg GetBucketUsedParams) (int32, error) {
	row := q.db.QueryRow(ctx, getBucketUsed, arg.InstanceID, arg.WindowStart)
	var used int32
	err := row.Scan(&used)
	return used, err
}

const lockBucket = `-- name: LockBucket :one
SELECT used FROM rate_buckets WHERE instance_id = $1 AND window_start = $2 FOR UPDATE
`

type LockBucketParams struct {
	InstanceID  uuid.UUID
	WindowStart time.Time
}

func (q *Queries) LockBucket(ctx context.Context, arg LockBucketParams) (int32, error) {
	row := q.db.QueryRow(ctx, lockBucket, arg.InstanceID, arg.WindowStart)
	var used int32
	err := row.Scan(&used)
	return used, err
}

const markProcessed = `-- name: MarkProcessed :exec
INSERT INTO processed_items (instance_id, kind, entity_type, entity_id, expires_at)
SELECT $1, $2, $3, c.id, $4
FROM unnest($5::bigint[]) AS c(id)
ON CONFLICT (instance_id, kind, entity_type, entity_id) DO UPDATE SET expires_at = EXCLUDED.expires_at
`

type MarkProcessedParams struct {
	InstanceID uuid.UUID
	Kind       string
	EntityType string
	ExpiresAt  time.Time
	EntityIds  []int64
}

func (q *Queries) MarkProcessed(ctx context.Context, arg MarkProcessedParams) error {
	_, err := q.db.Exec(ctx, markProcessed,
		arg.InstanceID,
		arg.Kind,
		arg.EntityType,
		arg.ExpiresAt,
		arg.EntityIds,
	)
	return err
}

const purgeBucketsBefore = `-- name: PurgeBucketsBefore :execrows
DELETE FROM rate_buckets WHERE window_start < $1
`

func (q *Queries) PurgeBucketsBefore(ctx context.Context, windowStart time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeBucketsBefore, windowStart)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeExpiredProcessed = `-- name: PurgeExpiredProcessed :execrows
DELETE FROM processed_items WHERE expires_at <= $1
`

func (q *Queries) PurgeExpiredProcessed(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredProcessed, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetProcessed = `-- name: ResetProcessed :execrows
DELETE FROM processed_items
WHERE ($1::uuid IS NULL OR instance_id = $1::uuid)
`

func (q *Queries) ResetProcessed(ctx context.Context, instanceID *uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, resetProcessed, instanceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setBucketUsed = `-- name: SetBucketUsed :exec
UPDATE rate_buckets SET used = $3 WHERE instance_id = $1 AND window_start = $2
`

type SetBucketUsedParams struct {
	InstanceID  uuid.UUID
	WindowStart time.Time
	Used        int32
}

func (q *Queries) SetBucketUsed(ctx context.Context, arg SetBucketUsedParams) error {
	_, err := q.db.Exec(ctx, setBucketUsed, arg.InstanceID, arg.WindowStart, arg.Used)
	return err
}
