// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memory.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addBucketUsed = `-- name: AddBucketUsed :exec
INSERT INTO rate_buckets (instance_id, window_start, used) VALUES ($1, $2, $3)
ON CONFLICT (instance_id, window_start) DO UPDATE SET used = rate_buckets.used + EXCLUDED.used
`

type AddBucketUsedParams struct {
	InstanceID  uuid.UUID
	WindowStart time.Time
	Used        int32
}

func (q *Queries) AddBucketUsed(ctx context.Context, arg AddBucketUsedParams) error {
	_, err := q.db.Exec(ctx, addBucketUsed, arg.InstanceID, arg.WindowStart, arg.Used)
	return err
}

const addGlobalBucketUsed = `-- name: AddGlobalBucketUsed :exec
INSERT INTO global_rate_buckets (window_start, used) VALUES ($1, $2)
ON CONFLICT (window_start) DO UPDATE SET used = global_rate_buckets.used + EXCLUDED.used
`

type AddGlobalBucketUsedParams struct {
	WindowStart time.Time
	Used        int32
}

func (q *Queries) AddGlobalBucketUsed(ctx context.Context, arg AddGlobalBucketUsedParams) error {
	_, err := q.db.Exec(ctx, addGlobalBucketUsed, arg.WindowStart, arg.Used)
	return err
}

const bucketUsage = `-- name: BucketUsage :one
SELECT COALESCE(sum(used), 0)::int AS used,
       COALESCE(min(window_start), $1::timestamptz)::timestamptz AS oldest
FROM rate_buckets
WHERE instance_id = $2 AND window_start >= $1::timestamptz AND used > 0
`

type BucketUsageParams struct {
	Since      time.Time
	InstanceID uuid.UUID
}

type BucketUsageRow struct {
	Used   int32
	Oldest time.Time
}

func (q *Queries) BucketUsage(ctx context.Context, arg BucketUsageParams) (BucketUsageRow, error) {
	row := q.db.QueryRow(ctx, bucketUsage, arg.Since, arg.InstanceID)
	var i BucketUsageRow
	err := row.Scan(&i.Used, &i.Oldest)
	return i, err
}

const countProcessed = `-- name: CountProcessed :one
SELECT count(*) FROM processed_items WHERE instance_id = $1 AND expires_at > $2
`

type CountProcessedParams struct {
	InstanceID uuid.UUID
	ExpiresAt  time.Time
}

func (q *Queries) CountProcessed(ctx context.Context, arg CountProcessedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProcessed, arg.InstanceID, arg.ExpiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const filterUnprocessed = `-- name: FilterUnprocessed :many

SELECT c.id::bigint AS entity_id
FROM unnest($1::bigint[]) AS c(id)
WHERE NOT EXISTS (
    SELECT 1 FROM processed_items p
    WHERE p.instance_id = $2
      AND p.kind = $3
      AND p.entity_type = $4
      AND p.entity_id = c.id
      AND p.expires_at > $5
)
`

type FilterUnprocessedParams struct {
	EntityIds  []int64
	InstanceID uuid.UUID
	Kind       string
	EntityType string
	Now        time.Time
}

// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
// SPDX-License-Identifier: EUPL-1.2
func (q *Queries) FilterUnprocessed(ctx context.Context, arg FilterUnprocessedParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, filterUnprocessed,
		arg.EntityIds,
		arg.InstanceID,
		arg.Kind,
		arg.EntityType,
		arg.Now,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var entity_id int64
		if err := rows.Scan(&entity_id); err != nil {
			return nil, err
		}
		items = append(items, entity_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const globalBucketUsage = `-- name: GlobalBucketUsage :one
SELECT COALESCE(sum(used), 0)::int AS used,
       COALESCE(min(window_start), $1::timestamptz)::timestamptz AS oldest
FROM global_rate_buckets
WHERE window_start >= $1::timestamptz AND used > 0
`

type GlobalBucketUsageRow struct {
	Used   int32
	Oldest time.Time
}

func (q *Queries) GlobalBucketUsage(ctx context.Context, since time.Time) (GlobalBucketUsageRow, error) {
	row := q.db.QueryRow(ctx, globalBucketUsage, since)
	var i GlobalBucketUsageRow
	err := row.Scan(&i.Used, &i.Oldest)
	return i, err
}

const lockGlobalBudget = `-- name: LockGlobalBudget :exec
SELECT pg_advisory_xact_lock(hashtextextended('snatcharr.budget:global', 0))
`

// Taken after LockInstanceBudget, never before, so the two locks cannot deadlock.
func (q *Queries) LockGlobalBudget(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockGlobalBudget)
	return err
}

const lockInstanceBudget = `-- name: LockInstanceBudget :exec
SELECT pg_advisory_xact_lock(hashtextextended('snatcharr.budget:' || $1::uuid::text, 0))
`

// Stamina is a rolling window of one-minute buckets (#16). Every grant for an instance
// runs under this transaction-scoped lock, so two grants on either side of a minute
// boundary (different bucket rows) still see each other.
func (q *Queries) LockInstanceBudget(ctx context.Context, instanceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockInstanceBudget, instanceID)
	return err
}

const markProcessed = `-- name: MarkProcessed :exec
INSERT INTO processed_items (instance_id, kind, entity_type, entity_id, expires_at, attempts, last_snatched_at)
SELECT $1, $2, $3, c.id,
       $4::timestamptz + make_interval(secs => $5::bigint), 1, $4::timestamptz
FROM unnest($6::bigint[]) AS c(id)
ON CONFLICT (instance_id, kind, entity_type, entity_id) DO UPDATE SET
    attempts = processed_items.attempts + 1,
    last_snatched_at = EXCLUDED.last_snatched_at,
    expires_at = EXCLUDED.last_snatched_at + make_interval(
        secs => LEAST($5::bigint * power(2, LEAST(processed_items.attempts, 20))::bigint, $7::bigint)
    )
`

type MarkProcessedParams struct {
	InstanceID uuid.UUID
	Kind       string
	EntityType string
	Now        time.Time
	BaseS      int64
	EntityIds  []int64
	MaxS       int64
}

// Afterglow backoff: the first snatch rests base_s seconds, every further snatch of the
// same item doubles the rest, capped at max_s.
func (q *Queries) MarkProcessed(ctx context.Context, arg MarkProcessedParams) error {
	_, err := q.db.Exec(ctx, markProcessed,
		arg.InstanceID,
		arg.Kind,
		arg.EntityType,
		arg.Now,
		arg.BaseS,
		arg.EntityIds,
		arg.MaxS,
	)
	return err
}

const processedAttempts = `-- name: ProcessedAttempts :one
SELECT COALESCE((
    SELECT attempts FROM processed_items
    WHERE instance_id = $1 AND kind = $2 AND entity_type = $3 AND entity_id = $4
), 0)::int AS attempts
`

type ProcessedAttemptsParams struct {
	InstanceID uuid.UUID
	Kind       string
	EntityType string
	EntityID   int64
}

func (q *Queries) ProcessedAttempts(ctx context.Context, arg ProcessedAttemptsParams) (int32, error) {
	row := q.db.QueryRow(ctx, processedAttempts,
		arg.InstanceID,
		arg.Kind,
		arg.EntityType,
		arg.EntityID,
	)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const purgeBucketsBefore = `-- name: PurgeBucketsBefore :execrows
DELETE FROM rate_buckets
WHERE (instance_id, window_start) IN (
    SELECT instance_id, window_start FROM rate_buckets
    WHERE window_start < $1::timestamptz LIMIT $2::int)
`

type PurgeBucketsBeforeParams struct {
	Before time.Time
	Batch  int32
}

func (q *Queries) PurgeBucketsBefore(ctx context.Context, arg PurgeBucketsBeforeParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeBucketsBefore, arg.Before, arg.Batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeExpiredProcessed = `-- name: PurgeExpiredProcessed :execrows
DELETE FROM processed_items
WHERE (instance_id, kind, entity_type, entity_id) IN (
    SELECT instance_id, kind, entity_type, entity_id FROM processed_items
    WHERE expires_at <= $1::timestamptz LIMIT $2::int)
  AND expires_at <= $1::timestamptz
`

type PurgeExpiredProcessedParams struct {
	Before time.Time
	Batch  int32
}

// The outer expires_at condition is repeated on purpose: Postgres re-checks it on a row a
// concurrent snatch extended meanwhile, so that row is kept.
func (q *Queries) PurgeExpiredProcessed(ctx context.Context, arg PurgeExpiredProcessedParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredProcessed, arg.Before, arg.Batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeGlobalBucketsBefore = `-- name: PurgeGlobalBucketsBefore :execrows
DELETE FROM global_rate_buckets
WHERE window_start IN (
    SELECT window_start FROM global_rate_buckets
    WHERE window_start < $1::timestamptz LIMIT $2::int)
`

type PurgeGlobalBucketsBeforeParams struct {
	Before time.Time
	Batch  int32
}

func (q *Queries) PurgeGlobalBucketsBefore(ctx context.Context, arg PurgeGlobalBucketsBeforeParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeGlobalBucketsBefore, arg.Before, arg.Batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetProcessed = `-- name: ResetProcessed :execrows
DELETE FROM processed_items
WHERE ($1::uuid IS NULL OR instance_id = $1::uuid)
`

func (q *Queries) ResetProcessed(ctx context.Context, instanceID *uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, resetProcessed, instanceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
