// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID        string
	OwnerID   uuid.UUID
	Scopes    []string
	Hash      []byte
	CreatedAt time.Time
	ExpiresAt *time.Time
	RevokedAt *time.Time
}

type DownloadClient struct {
	ID                 uuid.UUID
	InstanceID         *uuid.UUID
	Kind               string
	Name               string
	BaseUrl            string
	Username           string
	SecretEnc          []byte
	Enabled            bool
	Source             string
	RemoteID           *int32
	MaxActive          int32
	BandwidthBudgetBps int64
	LastCheckAt        *time.Time
	LastError          *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type HuntEvent struct {
	ID         int64
	RunID      *uuid.UUID
	InstanceID uuid.UUID
	Ts         time.Time
	Level      string
	Type       string
	EntityType string
	EntityID   int64
	Title      string
	Detail     string
}

type HuntPolicy struct {
	InstanceID         uuid.UUID
	MissingPerCycle    int32
	UpgradePerCycle    int32
	CycleIntervalS     int32
	HourlyCap          int32
	Selection          string
	MonitoredOnly      bool
	SkipFutureReleases bool
	RadarrReleaseType  string
	SonarrMissingMode  string
	SonarrUpgradeMode  string
	LidarrMissingMode  string
	ProcessedTtlH      int32
	MaxQueueSize       int32
	AwaitCommand       bool
	PageSize           int32
	CursorMissing      string
	CursorUpgrade      string
	UpdatedAt          time.Time
}

type HuntRun struct {
	ID             uuid.UUID
	InstanceID     uuid.UUID
	Kind           string
	Status         string
	LeasedBy       *string
	LeaseExpiresAt *time.Time
	QueuedAt       time.Time
	StartedAt      *time.Time
	FinishedAt     *time.Time
	SearchedCount  int32
	Error          *string
}

type Instance struct {
	ID              uuid.UUID
	Kind            string
	Name            string
	BaseUrl         string
	ApiKeyEnc       []byte
	Enabled         bool
	Source          string
	ConfigarrKey    *string
	LastSeenVersion *string
	LastCheckAt     *time.Time
	LastError       *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type ProcessedItem struct {
	InstanceID uuid.UUID
	Kind       string
	EntityType string
	EntityID   int64
	ExpiresAt  time.Time
}

type RateBucket struct {
	InstanceID  uuid.UUID
	WindowStart time.Time
	Used        int32
}

type Schedule struct {
	ID         uuid.UUID
	InstanceID *uuid.UUID
	Name       string
	DaysMask   int32
	StartTime  pgtype.Time
	EndTime    pgtype.Time
	Tz         string
	Action     string
	CapValue   *int32
	Enabled    bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Session struct {
	ID        string
	Data      []byte
	ExpiresAt time.Time
}

type Setting struct {
	Singleton            bool
	HistoryRetentionDays int32
	UserAgent            string
	UpdatedAt            time.Time
}

type User struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	Role         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
