// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: policies.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const ensureDefaultPolicy = `-- name: EnsureDefaultPolicy :one
INSERT INTO hunt_policies (instance_id, updated_at)
VALUES ($1, $2)
ON CONFLICT (instance_id) DO UPDATE SET instance_id = EXCLUDED.instance_id
RETURNING instance_id, missing_per_cycle, upgrade_per_cycle, cycle_interval_s, hourly_cap, selection, monitored_only, skip_future_releases, radarr_release_type, sonarr_missing_mode, sonarr_upgrade_mode, lidarr_missing_mode, processed_ttl_h, max_queue_size, await_command, page_size, cursor_missing, cursor_upgrade, updated_at
`

type EnsureDefaultPolicyParams struct {
	InstanceID uuid.UUID
	UpdatedAt  time.Time
}

func (q *Queries) EnsureDefaultPolicy(ctx context.Context, arg EnsureDefaultPolicyParams) (HuntPolicy, error) {
	row := q.db.QueryRow(ctx, ensureDefaultPolicy, arg.InstanceID, arg.UpdatedAt)
	var i HuntPolicy
	err := row.Scan(
		&i.InstanceID,
		&i.MissingPerCycle,
		&i.UpgradePerCycle,
		&i.CycleIntervalS,
		&i.HourlyCap,
		&i.Selection,
		&i.MonitoredOnly,
		&i.SkipFutureReleases,
		&i.RadarrReleaseType,
		&i.SonarrMissingMode,
		&i.SonarrUpgradeMode,
		&i.LidarrMissingMode,
		&i.ProcessedTtlH,
		&i.MaxQueueSize,
		&i.AwaitCommand,
		&i.PageSize,
		&i.CursorMissing,
		&i.CursorUpgrade,
		&i.UpdatedAt,
	)
	return i, err
}

const getPolicy = `-- name: GetPolicy :one

SELECT instance_id, missing_per_cycle, upgrade_per_cycle, cycle_interval_s, hourly_cap, selection, monitored_only, skip_future_releases, radarr_release_type, sonarr_missing_mode, sonarr_upgrade_mode, lidarr_missing_mode, processed_ttl_h, max_queue_size, await_command, page_size, cursor_missing, cursor_upgrade, updated_at FROM hunt_policies WHERE instance_id = $1
`

// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
// SPDX-License-Identifier: EUPL-1.2
func (q *Queries) GetPolicy(ctx context.Context, instanceID uuid.UUID) (HuntPolicy, error) {
	row := q.db.QueryRow(ctx, getPolicy, instanceID)
	var i HuntPolicy
	err := row.Scan(
		&i.InstanceID,
		&i.MissingPerCycle,
		&i.UpgradePerCycle,
		&i.CycleIntervalS,
		&i.HourlyCap,
		&i.Selection,
		&i.MonitoredOnly,
		&i.SkipFutureReleases,
		&i.RadarrReleaseType,
		&i.SonarrMissingMode,
		&i.SonarrUpgradeMode,
		&i.LidarrMissingMode,
		&i.ProcessedTtlH,
		&i.MaxQueueSize,
		&i.AwaitCommand,
		&i.PageSize,
		&i.CursorMissing,
		&i.CursorUpgrade,
		&i.UpdatedAt,
	)
	return i, err
}

const savePolicyCursor = `-- name: SavePolicyCursor :exec
UPDATE hunt_policies
SET cursor_missing = CASE WHEN $1::text = 'missing' THEN $2::text ELSE cursor_missing END,
    cursor_upgrade = CASE WHEN $1::text = 'upgrade' THEN $2::text ELSE cursor_upgrade END,
    updated_at = $3
WHERE instance_id = $4
`

type SavePolicyCursorParams struct {
	Kind       string
	Cursor     string
	UpdatedAt  time.Time
	InstanceID uuid.UUID
}

func (q *Queries) SavePolicyCursor(ctx context.Context, arg SavePolicyCursorParams) error {
	_, err := q.db.Exec(ctx, savePolicyCursor,
		arg.Kind,
		arg.Cursor,
		arg.UpdatedAt,
		arg.InstanceID,
	)
	return err
}

const upsertPolicy = `-- name: UpsertPolicy :one
INSERT INTO hunt_policies (
    instance_id, missing_per_cycle, upgrade_per_cycle, cycle_interval_s, hourly_cap, selection,
    monitored_only, skip_future_releases, radarr_release_type, sonarr_missing_mode, sonarr_upgrade_mode,
    lidarr_missing_mode, processed_ttl_h, max_queue_size, await_command, page_size, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16, $17
)
ON CONFLICT (instance_id) DO UPDATE SET
    missing_per_cycle = EXCLUDED.missing_per_cycle,
    upgrade_per_cycle = EXCLUDED.upgrade_per_cycle,
    cycle_interval_s = EXCLUDED.cycle_interval_s,
    hourly_cap = EXCLUDED.hourly_cap,
    selection = EXCLUDED.selection,
    monitored_only = EXCLUDED.monitored_only,
    skip_future_releases = EXCLUDED.skip_future_releases,
    radarr_release_type = EXCLUDED.radarr_release_type,
    sonarr_missing_mode = EXCLUDED.sonarr_missing_mode,
    sonarr_upgrade_mode = EXCLUDED.sonarr_upgrade_mode,
    lidarr_missing_mode = EXCLUDED.lidarr_missing_mode,
    processed_ttl_h = EXCLUDED.processed_ttl_h,
    max_queue_size = EXCLUDED.max_queue_size,
    await_command = EXCLUDED.await_command,
    page_size = EXCLUDED.page_size,
    updated_at = EXCLUDED.updated_at
RETURNING instance_id, missing_per_cycle, upgrade_per_cycle, cycle_interval_s, hourly_cap, selection, monitored_only, skip_future_releases, radarr_release_type, sonarr_missing_mode, sonarr_upgrade_mode, lidarr_missing_mode, processed_ttl_h, max_queue_size, await_command, page_size, cursor_missing, cursor_upgrade, updated_at
`

type UpsertPolicyParams struct {
	InstanceID         uuid.UUID
	MissingPerCycle    int32
	UpgradePerCycle    int32
	CycleIntervalS     int32
	HourlyCap          int32
	Selection          string
	MonitoredOnly      bool
	SkipFutureReleases bool
	RadarrReleaseType  string
	SonarrMissingMode  string
	SonarrUpgradeMode  string
	LidarrMissingMode  string
	ProcessedTtlH      int32
	MaxQueueSize       int32
	AwaitCommand       bool
	PageSize           int32
	UpdatedAt          time.Time
}

func (q *Queries) UpsertPolicy(ctx context.Context, arg UpsertPolicyParams) (HuntPolicy, error) {
	row := q.db.QueryRow(ctx, upsertPolicy,
		arg.InstanceID,
		arg.MissingPerCycle,
		arg.UpgradePerCycle,
		arg.CycleIntervalS,
		arg.HourlyCap,
		arg.Selection,
		arg.MonitoredOnly,
		arg.SkipFutureReleases,
		arg.RadarrReleaseType,
		arg.SonarrMissingMode,
		arg.SonarrUpgradeMode,
		arg.LidarrMissingMode,
		arg.ProcessedTtlH,
		arg.MaxQueueSize,
		arg.AwaitCommand,
		arg.PageSize,
		arg.UpdatedAt,
	)
	var i HuntPolicy
	err := row.Scan(
		&i.InstanceID,
		&i.MissingPerCycle,
		&i.UpgradePerCycle,
		&i.CycleIntervalS,
		&i.HourlyCap,
		&i.Selection,
		&i.MonitoredOnly,
		&i.SkipFutureReleases,
		&i.RadarrReleaseType,
		&i.SonarrMissingMode,
		&i.SonarrUpgradeMode,
		&i.LidarrMissingMode,
		&i.ProcessedTtlH,
		&i.MaxQueueSize,
		&i.AwaitCommand,
		&i.PageSize,
		&i.CursorMissing,
		&i.CursorUpgrade,
		&i.UpdatedAt,
	)
	return i, err
}
