// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	CountInstancesByBaseURL(ctx context.Context, arg CountInstancesByBaseURLParams) (int64, error)
	// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
	// SPDX-License-Identifier: EUPL-1.2
	CountUsers(ctx context.Context) (int64, error)
	// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
	// SPDX-License-Identifier: EUPL-1.2
	CreateInstance(ctx context.Context, arg CreateInstanceParams) (Instance, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteInstance(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteSession(ctx context.Context, id string) error
	EnsureDefaultPolicy(ctx context.Context, arg EnsureDefaultPolicyParams) (HuntPolicy, error)
	EnsureSettings(ctx context.Context, updatedAt time.Time) (Setting, error)
	GetAPIKey(ctx context.Context, id string) (ApiKey, error)
	GetInstance(ctx context.Context, id uuid.UUID) (Instance, error)
	GetInstanceByConfigarrKey(ctx context.Context, configarrKey *string) (Instance, error)
	// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
	// SPDX-License-Identifier: EUPL-1.2
	GetPolicy(ctx context.Context, instanceID uuid.UUID) (HuntPolicy, error)
	// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
	// SPDX-License-Identifier: EUPL-1.2
	GetSettings(ctx context.Context) (Setting, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListAPIKeysByOwner(ctx context.Context, ownerID uuid.UUID) ([]ApiKey, error)
	ListEnabledInstances(ctx context.Context) ([]Instance, error)
	ListInstances(ctx context.Context) ([]Instance, error)
	ListUsers(ctx context.Context) ([]User, error)
	LoadSession(ctx context.Context, arg LoadSessionParams) ([]byte, error)
	PurgeExpiredSessions(ctx context.Context, expiresAt time.Time) (int64, error)
	RecordInstanceCheck(ctx context.Context, arg RecordInstanceCheckParams) error
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error)
	SaveAPIKey(ctx context.Context, arg SaveAPIKeyParams) error
	SavePolicyCursor(ctx context.Context, arg SavePolicyCursorParams) error
	SaveSession(ctx context.Context, arg SaveSessionParams) error
	UpdateInstance(ctx context.Context, arg UpdateInstanceParams) (Instance, error)
	UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (Setting, error)
	UpsertConfigarrInstance(ctx context.Context, arg UpsertConfigarrInstanceParams) (Instance, error)
	UpsertPolicy(ctx context.Context, arg UpsertPolicyParams) (HuntPolicy, error)
}

var _ Querier = (*Queries)(nil)
