// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	CancelRun(ctx context.Context, arg CancelRunParams) (int64, error)
	CompleteRun(ctx context.Context, arg CompleteRunParams) (SnatchRun, error)
	CountInstancesByBaseURL(ctx context.Context, arg CountInstancesByBaseURLParams) (int64, error)
	CountInstancesByBaseURLAndNotSource(ctx context.Context, arg CountInstancesByBaseURLAndNotSourceParams) (int64, error)
	CountProcessed(ctx context.Context, arg CountProcessedParams) (int64, error)
	CountSeerrRequests(ctx context.Context, linkID uuid.UUID) (int64, error)
	// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
	// SPDX-License-Identifier: EUPL-1.2
	CountUsers(ctx context.Context) (int64, error)
	// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
	// SPDX-License-Identifier: EUPL-1.2
	CreateCleanuparrLink(ctx context.Context, arg CreateCleanuparrLinkParams) (CleanuparrLink, error)
	// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
	// SPDX-License-Identifier: EUPL-1.2
	CreateDownloadClient(ctx context.Context, arg CreateDownloadClientParams) (DownloadClient, error)
	// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
	// SPDX-License-Identifier: EUPL-1.2
	CreateInstance(ctx context.Context, arg CreateInstanceParams) (Instance, error)
	// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
	// SPDX-License-Identifier: EUPL-1.2
	CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error)
	// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
	// SPDX-License-Identifier: EUPL-1.2
	CreateSeerrLink(ctx context.Context, arg CreateSeerrLinkParams) (SeerrLink, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCleanuparrLink(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteDownloadClient(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteEventsForInstance(ctx context.Context, instanceID uuid.UUID) (int64, error)
	DeleteInstance(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteSchedule(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteSeerrLink(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteSession(ctx context.Context, id string) error
	DeleteStaleDiscoveredDownloadClients(ctx context.Context, arg DeleteStaleDiscoveredDownloadClientsParams) (int64, error)
	DeleteUnseenSeerrRequests(ctx context.Context, arg DeleteUnseenSeerrRequestsParams) (int64, error)
	DisableConfigarrInstancesNotIn(ctx context.Context, arg DisableConfigarrInstancesNotInParams) (int64, error)
	// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
	// SPDX-License-Identifier: EUPL-1.2
	EnqueueRun(ctx context.Context, arg EnqueueRunParams) (SnatchRun, error)
	EnsureBucket(ctx context.Context, arg EnsureBucketParams) error
	EnsureDefaultPolicy(ctx context.Context, arg EnsureDefaultPolicyParams) (SnatchPolicy, error)
	EnsureGlobalBucket(ctx context.Context, windowStart time.Time) error
	EnsureSettings(ctx context.Context, updatedAt time.Time) (Setting, error)
	// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
	// SPDX-License-Identifier: EUPL-1.2
	FilterUnprocessed(ctx context.Context, arg FilterUnprocessedParams) ([]int64, error)
	GetAPIKey(ctx context.Context, id string) (ApiKey, error)
	GetBucketUsed(ctx context.Context, arg GetBucketUsedParams) (int32, error)
	GetCleanuparrLink(ctx context.Context, id uuid.UUID) (CleanuparrLink, error)
	GetDownloadClient(ctx context.Context, id uuid.UUID) (DownloadClient, error)
	GetGlobalBucketUsed(ctx context.Context, windowStart time.Time) (int32, error)
	GetInstance(ctx context.Context, id uuid.UUID) (Instance, error)
	GetInstanceByConfigarrKey(ctx context.Context, configarrKey *string) (Instance, error)
	// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
	// SPDX-License-Identifier: EUPL-1.2
	GetPolicy(ctx context.Context, instanceID uuid.UUID) (SnatchPolicy, error)
	GetRun(ctx context.Context, id uuid.UUID) (SnatchRun, error)
	GetSchedule(ctx context.Context, id uuid.UUID) (Schedule, error)
	GetSeerrLink(ctx context.Context, id uuid.UUID) (SeerrLink, error)
	GetSeerrRequest(ctx context.Context, arg GetSeerrRequestParams) (SeerrRequest, error)
	GetSeerrRequestTitle(ctx context.Context, arg GetSeerrRequestTitleParams) (string, error)
	// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
	// SPDX-License-Identifier: EUPL-1.2
	GetSettings(ctx context.Context) (Setting, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	HasActiveRun(ctx context.Context, arg HasActiveRunParams) (bool, error)
	HeartbeatRun(ctx context.Context, arg HeartbeatRunParams) (SnatchRun, error)
	// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
	// SPDX-License-Identifier: EUPL-1.2
	InsertEvent(ctx context.Context, arg InsertEventParams) (int64, error)
	LastFinishedAt(ctx context.Context, arg LastFinishedAtParams) (time.Time, error)
	LeaseRun(ctx context.Context, arg LeaseRunParams) (SnatchRun, error)
	ListAPIKeysByOwner(ctx context.Context, ownerID uuid.UUID) ([]ApiKey, error)
	ListCleanuparrLinks(ctx context.Context) ([]CleanuparrLink, error)
	ListDownloadClients(ctx context.Context) ([]DownloadClient, error)
	ListDownloadClientsForInstance(ctx context.Context, instanceID *uuid.UUID) ([]DownloadClient, error)
	ListEnabledCleanuparrLinks(ctx context.Context) ([]CleanuparrLink, error)
	ListEnabledDownloadClients(ctx context.Context) ([]DownloadClient, error)
	ListEnabledInstances(ctx context.Context) ([]Instance, error)
	ListEnabledSchedulesFor(ctx context.Context, instanceID *uuid.UUID) ([]Schedule, error)
	ListEnabledSeerrLinks(ctx context.Context) ([]SeerrLink, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]SnatchEvent, error)
	ListInstances(ctx context.Context) ([]Instance, error)
	ListRuns(ctx context.Context, arg ListRunsParams) ([]SnatchRun, error)
	ListSchedules(ctx context.Context) ([]Schedule, error)
	ListSeerrLinks(ctx context.Context) ([]SeerrLink, error)
	ListSeerrRequests(ctx context.Context, limit int32) ([]ListSeerrRequestsRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	LoadSession(ctx context.Context, arg LoadSessionParams) ([]byte, error)
	LockBucket(ctx context.Context, arg LockBucketParams) (int32, error)
	LockGlobalBucket(ctx context.Context, windowStart time.Time) (int32, error)
	// Afterglow backoff: the first snatch rests base_s seconds, every further snatch of the
	// same item doubles the rest, capped at max_s.
	MarkProcessed(ctx context.Context, arg MarkProcessedParams) error
	MarkSeerrRequestsSnatched(ctx context.Context, arg MarkSeerrRequestsSnatchedParams) (int64, error)
	PriorityEntityIDs(ctx context.Context, instanceID *uuid.UUID) ([]int64, error)
	ProcessedAttempts(ctx context.Context, arg ProcessedAttemptsParams) (int32, error)
	PurgeBucketsBefore(ctx context.Context, windowStart time.Time) (int64, error)
	PurgeEventsBefore(ctx context.Context, ts time.Time) (int64, error)
	PurgeExpiredProcessed(ctx context.Context, expiresAt time.Time) (int64, error)
	PurgeExpiredSessions(ctx context.Context, expiresAt time.Time) (int64, error)
	PurgeGlobalBucketsBefore(ctx context.Context, windowStart time.Time) (int64, error)
	PurgeRunsBefore(ctx context.Context, finishedAt *time.Time) (int64, error)
	RecentRunStatuses(ctx context.Context, arg RecentRunStatusesParams) ([]string, error)
	RecordCleanuparrCheck(ctx context.Context, arg RecordCleanuparrCheckParams) error
	RecordDownloadClientCheck(ctx context.Context, arg RecordDownloadClientCheckParams) error
	RecordInstanceCheck(ctx context.Context, arg RecordInstanceCheckParams) error
	RecordSeerrCheck(ctx context.Context, arg RecordSeerrCheckParams) error
	RecordSeerrSync(ctx context.Context, arg RecordSeerrSyncParams) error
	ResetProcessed(ctx context.Context, instanceID *uuid.UUID) (int64, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error)
	SaveAPIKey(ctx context.Context, arg SaveAPIKeyParams) error
	SavePolicyCursor(ctx context.Context, arg SavePolicyCursorParams) error
	SaveSession(ctx context.Context, arg SaveSessionParams) error
	SetBucketUsed(ctx context.Context, arg SetBucketUsedParams) error
	SetGlobalBucketUsed(ctx context.Context, arg SetGlobalBucketUsedParams) error
	UpdateCleanuparrLink(ctx context.Context, arg UpdateCleanuparrLinkParams) (CleanuparrLink, error)
	UpdateDownloadClient(ctx context.Context, arg UpdateDownloadClientParams) (DownloadClient, error)
	UpdateInstance(ctx context.Context, arg UpdateInstanceParams) (Instance, error)
	UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (Schedule, error)
	UpdateSeerrLink(ctx context.Context, arg UpdateSeerrLinkParams) (SeerrLink, error)
	UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (Setting, error)
	UpsertConfigarrInstance(ctx context.Context, arg UpsertConfigarrInstanceParams) (UpsertConfigarrInstanceRow, error)
	UpsertDiscoveredDownloadClient(ctx context.Context, arg UpsertDiscoveredDownloadClientParams) (UpsertDiscoveredDownloadClientRow, error)
	UpsertPolicy(ctx context.Context, arg UpsertPolicyParams) (SnatchPolicy, error)
	UpsertSeerrRequest(ctx context.Context, arg UpsertSeerrRequestParams) error
}

var _ Querier = (*Queries)(nil)
