// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelRun = `-- name: CancelRun :execrows
UPDATE snatch_runs SET status = 'cancelled', finished_at = $2
WHERE id = $1 AND status IN ('queued', 'leased')
`

type CancelRunParams struct {
	ID         uuid.UUID
	FinishedAt *time.Time
}

func (q *Queries) CancelRun(ctx context.Context, arg CancelRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelRun, arg.ID, arg.FinishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeRun = `-- name: CompleteRun :one
UPDATE snatch_runs
SET status = $3, finished_at = $4, searched_count = $5, error = $6, lease_expires_at = NULL
WHERE id = $1 AND leased_by = $2 AND status IN ('leased', 'cancelled')
RETURNING id, instance_id, kind, status, leased_by, lease_expires_at, queued_at, started_at, finished_at, searched_count, error
`

type CompleteRunParams struct {
	ID            uuid.UUID
	LeasedBy      *string
	Status        string
	FinishedAt    *time.Time
	SearchedCount int32
	Error         *string
}

func (q *Queries) CompleteRun(ctx context.Context, arg CompleteRunParams) (SnatchRun, error) {
	row := q.db.QueryRow(ctx, completeRun,
		arg.ID,
		arg.LeasedBy,
		arg.Status,
		arg.FinishedAt,
		arg.SearchedCount,
		arg.Error,
	)
	var i SnatchRun
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Kind,
		&i.Status,
		&i.LeasedBy,
		&i.LeaseExpiresAt,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SearchedCount,
		&i.Error,
	)
	return i, err
}

const enqueueRun = `-- name: EnqueueRun :one

INSERT INTO snatch_runs (id, instance_id, kind, status, queued_at)
VALUES ($1, $2, $3, 'queued', $4)
RETURNING id, instance_id, kind, status, leased_by, lease_expires_at, queued_at, started_at, finished_at, searched_count, error
`

type EnqueueRunParams struct {
	ID         uuid.UUID
	InstanceID uuid.UUID
	Kind       string
	QueuedAt   time.Time
}

// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
// SPDX-License-Identifier: EUPL-1.2
func (q *Queries) EnqueueRun(ctx context.Context, arg EnqueueRunParams) (SnatchRun, error) {
	row := q.db.QueryRow(ctx, enqueueRun,
		arg.ID,
		arg.InstanceID,
		arg.Kind,
		arg.QueuedAt,
	)
	var i SnatchRun
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Kind,
		&i.Status,
		&i.LeasedBy,
		&i.LeaseExpiresAt,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SearchedCount,
		&i.Error,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, instance_id, kind, status, leased_by, lease_expires_at, queued_at, started_at, finished_at, searched_count, error FROM snatch_runs WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id uuid.UUID) (SnatchRun, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i SnatchRun
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Kind,
		&i.Status,
		&i.LeasedBy,
		&i.LeaseExpiresAt,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SearchedCount,
		&i.Error,
	)
	return i, err
}

const hasActiveRun = `-- name: HasActiveRun :one
SELECT EXISTS (
    SELECT 1 FROM snatch_runs
    WHERE instance_id = $1 AND kind = $2 AND status IN ('queued', 'leased')
)
`

type HasActiveRunParams struct {
	InstanceID uuid.UUID
	Kind       string
}

func (q *Queries) HasActiveRun(ctx context.Context, arg HasActiveRunParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveRun, arg.InstanceID, arg.Kind)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const heartbeatRun = `-- name: HeartbeatRun :one
UPDATE snatch_runs
SET lease_expires_at = $3
WHERE id = $1 AND leased_by = $2 AND status = 'leased'
RETURNING id, instance_id, kind, status, leased_by, lease_expires_at, queued_at, started_at, finished_at, searched_count, error
`

type HeartbeatRunParams struct {
	ID             uuid.UUID
	LeasedBy       *string
	LeaseExpiresAt *time.Time
}

func (q *Queries) HeartbeatRun(ctx context.Context, arg HeartbeatRunParams) (SnatchRun, error) {
	row := q.db.QueryRow(ctx, heartbeatRun, arg.ID, arg.LeasedBy, arg.LeaseExpiresAt)
	var i SnatchRun
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Kind,
		&i.Status,
		&i.LeasedBy,
		&i.LeaseExpiresAt,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SearchedCount,
		&i.Error,
	)
	return i, err
}

const lastFinishedAt = `-- name: LastFinishedAt :one
SELECT COALESCE(max(finished_at), '1970-01-01'::timestamptz)::timestamptz AS last_finished
FROM snatch_runs
WHERE instance_id = $1 AND kind = $2 AND status IN ('done', 'failed')
`

type LastFinishedAtParams struct {
	InstanceID uuid.UUID
	Kind       string
}

func (q *Queries) LastFinishedAt(ctx context.Context, arg LastFinishedAtParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, lastFinishedAt, arg.InstanceID, arg.Kind)
	var last_finished time.Time
	err := row.Scan(&last_finished)
	return last_finished, err
}

const leaseRun = `-- name: LeaseRun :one
UPDATE snatch_runs
SET status = 'leased', leased_by = $1, lease_expires_at = $2, started_at = COALESCE(started_at, $3)
WHERE id = (
    SELECT id FROM snatch_runs
    WHERE status = 'queued' OR (status = 'leased' AND lease_expires_at < $3)
    ORDER BY queued_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, instance_id, kind, status, leased_by, lease_expires_at, queued_at, started_at, finished_at, searched_count, error
`

type LeaseRunParams struct {
	LeasedBy       *string
	LeaseExpiresAt *time.Time
	StartedAt      *time.Time
}

func (q *Queries) LeaseRun(ctx context.Context, arg LeaseRunParams) (SnatchRun, error) {
	row := q.db.QueryRow(ctx, leaseRun, arg.LeasedBy, arg.LeaseExpiresAt, arg.StartedAt)
	var i SnatchRun
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Kind,
		&i.Status,
		&i.LeasedBy,
		&i.LeaseExpiresAt,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SearchedCount,
		&i.Error,
	)
	return i, err
}

const listRuns = `-- name: ListRuns :many
SELECT id, instance_id, kind, status, leased_by, lease_expires_at, queued_at, started_at, finished_at, searched_count, error FROM snatch_runs
WHERE ($3::uuid IS NULL OR instance_id = $3::uuid)
ORDER BY queued_at DESC
LIMIT $1 OFFSET $2
`

type ListRunsParams struct {
	Limit      int32
	Offset     int32
	InstanceID *uuid.UUID
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]SnatchRun, error) {
	rows, err := q.db.Query(ctx, listRuns, arg.Limit, arg.Offset, arg.InstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SnatchRun{}
	for rows.Next() {
		var i SnatchRun
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Kind,
			&i.Status,
			&i.LeasedBy,
			&i.LeaseExpiresAt,
			&i.QueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.SearchedCount,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeRunsBefore = `-- name: PurgeRunsBefore :execrows
DELETE FROM snatch_runs WHERE status IN ('done', 'failed', 'cancelled') AND finished_at < $1
`

func (q *Queries) PurgeRunsBefore(ctx context.Context, finishedAt *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeRunsBefore, finishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recentRunStatuses = `-- name: RecentRunStatuses :many
SELECT status FROM snatch_runs
WHERE instance_id = $1 AND kind = $2 AND status IN ('done', 'failed')
ORDER BY finished_at DESC
LIMIT 10
`

type RecentRunStatusesParams struct {
	InstanceID uuid.UUID
	Kind       string
}

func (q *Queries) RecentRunStatuses(ctx context.Context, arg RecentRunStatusesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, recentRunStatuses, arg.InstanceID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var status string
		if err := rows.Scan(&status); err != nil {
			return nil, err
		}
		items = append(items, status)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
