// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedules.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSchedule = `-- name: CreateSchedule :one

INSERT INTO schedules (id, instance_id, name, days_mask, start_time, end_time, tz, action, cap_value, enabled, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $11)
RETURNING id, instance_id, name, days_mask, start_time, end_time, tz, action, cap_value, enabled, created_at, updated_at
`

type CreateScheduleParams struct {
	ID         uuid.UUID
	InstanceID *uuid.UUID
	Name       string
	DaysMask   int32
	StartTime  pgtype.Time
	EndTime    pgtype.Time
	Tz         string
	Action     string
	CapValue   *int32
	Enabled    bool
	CreatedAt  time.Time
}

// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
// SPDX-License-Identifier: EUPL-1.2
func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.ID,
		arg.InstanceID,
		arg.Name,
		arg.DaysMask,
		arg.StartTime,
		arg.EndTime,
		arg.Tz,
		arg.Action,
		arg.CapValue,
		arg.Enabled,
		arg.CreatedAt,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Name,
		&i.DaysMask,
		&i.StartTime,
		&i.EndTime,
		&i.Tz,
		&i.Action,
		&i.CapValue,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :execrows
DELETE FROM schedules WHERE id = $1
`

func (q *Queries) DeleteSchedule(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSchedule, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, instance_id, name, days_mask, start_time, end_time, tz, action, cap_value, enabled, created_at, updated_at FROM schedules WHERE id = $1
`

func (q *Queries) GetSchedule(ctx context.Context, id uuid.UUID) (Schedule, error) {
	row := q.db.QueryRow(ctx, getSchedule, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Name,
		&i.DaysMask,
		&i.StartTime,
		&i.EndTime,
		&i.Tz,
		&i.Action,
		&i.CapValue,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledSchedulesFor = `-- name: ListEnabledSchedulesFor :many
SELECT id, instance_id, name, days_mask, start_time, end_time, tz, action, cap_value, enabled, created_at, updated_at FROM schedules WHERE enabled AND (instance_id IS NULL OR instance_id = $1)
`

func (q *Queries) ListEnabledSchedulesFor(ctx context.Context, instanceID *uuid.UUID) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listEnabledSchedulesFor, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Name,
			&i.DaysMask,
			&i.StartTime,
			&i.EndTime,
			&i.Tz,
			&i.Action,
			&i.CapValue,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, instance_id, name, days_mask, start_time, end_time, tz, action, cap_value, enabled, created_at, updated_at FROM schedules ORDER BY name
`

func (q *Queries) ListSchedules(ctx context.Context) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Name,
			&i.DaysMask,
			&i.StartTime,
			&i.EndTime,
			&i.Tz,
			&i.Action,
			&i.CapValue,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchedule = `-- name: UpdateSchedule :one
UPDATE schedules
SET instance_id = $2, name = $3, days_mask = $4, start_time = $5, end_time = $6, tz = $7,
    action = $8, cap_value = $9, enabled = $10, updated_at = $11
WHERE id = $1
RETURNING id, instance_id, name, days_mask, start_time, end_time, tz, action, cap_value, enabled, created_at, updated_at
`

type UpdateScheduleParams struct {
	ID         uuid.UUID
	InstanceID *uuid.UUID
	Name       string
	DaysMask   int32
	StartTime  pgtype.Time
	EndTime    pgtype.Time
	Tz         string
	Action     string
	CapValue   *int32
	Enabled    bool
	UpdatedAt  time.Time
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, updateSchedule,
		arg.ID,
		arg.InstanceID,
		arg.Name,
		arg.DaysMask,
		arg.StartTime,
		arg.EndTime,
		arg.Tz,
		arg.Action,
		arg.CapValue,
		arg.Enabled,
		arg.UpdatedAt,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Name,
		&i.DaysMask,
		&i.StartTime,
		&i.EndTime,
		&i.Tz,
		&i.Action,
		&i.CapValue,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
