// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seerr.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countSeerrRequests = `-- name: CountSeerrRequests :one
SELECT count(*) FROM seerr_requests WHERE link_id = $1
`

func (q *Queries) CountSeerrRequests(ctx context.Context, linkID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSeerrRequests, linkID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSeerrLink = `-- name: CreateSeerrLink :one

INSERT INTO seerr_links (id, name, base_url, api_key_enc, enabled, sonarr_instance_id, radarr_instance_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $8)
RETURNING id, name, base_url, api_key_enc, enabled, sonarr_instance_id, radarr_instance_id, last_seen_version, last_check_at, last_error, last_sync_at, created_at, updated_at
`

type CreateSeerrLinkParams struct {
	ID               uuid.UUID
	Name             string
	BaseUrl          string
	ApiKeyEnc        []byte
	Enabled          bool
	SonarrInstanceID *uuid.UUID
	RadarrInstanceID *uuid.UUID
	CreatedAt        time.Time
}

// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
// SPDX-License-Identifier: EUPL-1.2
func (q *Queries) CreateSeerrLink(ctx context.Context, arg CreateSeerrLinkParams) (SeerrLink, error) {
	row := q.db.QueryRow(ctx, createSeerrLink,
		arg.ID,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKeyEnc,
		arg.Enabled,
		arg.SonarrInstanceID,
		arg.RadarrInstanceID,
		arg.CreatedAt,
	)
	var i SeerrLink
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyEnc,
		&i.Enabled,
		&i.SonarrInstanceID,
		&i.RadarrInstanceID,
		&i.LastSeenVersion,
		&i.LastCheckAt,
		&i.LastError,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSeerrLink = `-- name: DeleteSeerrLink :execrows
DELETE FROM seerr_links WHERE id = $1
`

func (q *Queries) DeleteSeerrLink(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSeerrLink, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUnseenSeerrRequests = `-- name: DeleteUnseenSeerrRequests :execrows
DELETE FROM seerr_requests WHERE link_id = $1 AND last_seen_at < $2
`

type DeleteUnseenSeerrRequestsParams struct {
	LinkID     uuid.UUID
	LastSeenAt time.Time
}

func (q *Queries) DeleteUnseenSeerrRequests(ctx context.Context, arg DeleteUnseenSeerrRequestsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUnseenSeerrRequests, arg.LinkID, arg.LastSeenAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSeerrLink = `-- name: GetSeerrLink :one
SELECT id, name, base_url, api_key_enc, enabled, sonarr_instance_id, radarr_instance_id, last_seen_version, last_check_at, last_error, last_sync_at, created_at, updated_at FROM seerr_links WHERE id = $1
`

func (q *Queries) GetSeerrLink(ctx context.Context, id uuid.UUID) (SeerrLink, error) {
	row := q.db.QueryRow(ctx, getSeerrLink, id)
	var i SeerrLink
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyEnc,
		&i.Enabled,
		&i.SonarrInstanceID,
		&i.RadarrInstanceID,
		&i.LastSeenVersion,
		&i.LastCheckAt,
		&i.LastError,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSeerrRequest = `-- name: GetSeerrRequest :one
SELECT link_id, request_id, media_type, tmdb_id, tvdb_id, title, request_status, media_status, is_4k, requested_by, seasons, seerr_server_id, instance_id, entity_id, requested_at, last_snatched_at, last_seen_at, updated_at FROM seerr_requests WHERE link_id = $1 AND request_id = $2
`

type GetSeerrRequestParams struct {
	LinkID    uuid.UUID
	RequestID int32
}

func (q *Queries) GetSeerrRequest(ctx context.Context, arg GetSeerrRequestParams) (SeerrRequest, error) {
	row := q.db.QueryRow(ctx, getSeerrRequest, arg.LinkID, arg.RequestID)
	var i SeerrRequest
	err := row.Scan(
		&i.LinkID,
		&i.RequestID,
		&i.MediaType,
		&i.TmdbID,
		&i.TvdbID,
		&i.Title,
		&i.RequestStatus,
		&i.MediaStatus,
		&i.Is4k,
		&i.RequestedBy,
		&i.Seasons,
		&i.SeerrServerID,
		&i.InstanceID,
		&i.EntityID,
		&i.RequestedAt,
		&i.LastSnatchedAt,
		&i.LastSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSeerrRequestTitle = `-- name: GetSeerrRequestTitle :one
SELECT title FROM seerr_requests WHERE link_id = $1 AND request_id = $2
`

type GetSeerrRequestTitleParams struct {
	LinkID    uuid.UUID
	RequestID int32
}

func (q *Queries) GetSeerrRequestTitle(ctx context.Context, arg GetSeerrRequestTitleParams) (string, error) {
	row := q.db.QueryRow(ctx, getSeerrRequestTitle, arg.LinkID, arg.RequestID)
	var title string
	err := row.Scan(&title)
	return title, err
}

const listEnabledSeerrLinks = `-- name: ListEnabledSeerrLinks :many
SELECT id, name, base_url, api_key_enc, enabled, sonarr_instance_id, radarr_instance_id, last_seen_version, last_check_at, last_error, last_sync_at, created_at, updated_at FROM seerr_links WHERE enabled ORDER BY name
`

func (q *Queries) ListEnabledSeerrLinks(ctx context.Context) ([]SeerrLink, error) {
	rows, err := q.db.Query(ctx, listEnabledSeerrLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SeerrLink{}
	for rows.Next() {
		var i SeerrLink
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.ApiKeyEnc,
			&i.Enabled,
			&i.SonarrInstanceID,
			&i.RadarrInstanceID,
			&i.LastSeenVersion,
			&i.LastCheckAt,
			&i.LastError,
			&i.LastSyncAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeerrLinks = `-- name: ListSeerrLinks :many
SELECT id, name, base_url, api_key_enc, enabled, sonarr_instance_id, radarr_instance_id, last_seen_version, last_check_at, last_error, last_sync_at, created_at, updated_at FROM seerr_links ORDER BY name
`

func (q *Queries) ListSeerrLinks(ctx context.Context) ([]SeerrLink, error) {
	rows, err := q.db.Query(ctx, listSeerrLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SeerrLink{}
	for rows.Next() {
		var i SeerrLink
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.ApiKeyEnc,
			&i.Enabled,
			&i.SonarrInstanceID,
			&i.RadarrInstanceID,
			&i.LastSeenVersion,
			&i.LastCheckAt,
			&i.LastError,
			&i.LastSyncAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeerrRequests = `-- name: ListSeerrRequests :many
SELECT r.link_id, r.request_id, r.media_type, r.tmdb_id, r.tvdb_id, r.title, r.request_status, r.media_status, r.is_4k, r.requested_by, r.seasons, r.seerr_server_id, r.instance_id, r.entity_id, r.requested_at, r.last_snatched_at, r.last_seen_at, r.updated_at, l.name AS link_name, i.name AS instance_name
FROM seerr_requests r
JOIN seerr_links l ON l.id = r.link_id
LEFT JOIN instances i ON i.id = r.instance_id
ORDER BY r.requested_at DESC NULLS LAST, r.request_id DESC
LIMIT $1
`

type ListSeerrRequestsRow struct {
	LinkID         uuid.UUID
	RequestID      int32
	MediaType      string
	TmdbID         int32
	TvdbID         int32
	Title          string
	RequestStatus  int32
	MediaStatus    int32
	Is4k           bool
	RequestedBy    string
	Seasons        []int32
	SeerrServerID  *int32
	InstanceID     *uuid.UUID
	EntityID       *int64
	RequestedAt    *time.Time
	LastSnatchedAt *time.Time
	LastSeenAt     time.Time
	UpdatedAt      time.Time
	LinkName       string
	InstanceName   *string
}

func (q *Queries) ListSeerrRequests(ctx context.Context, limit int32) ([]ListSeerrRequestsRow, error) {
	rows, err := q.db.Query(ctx, listSeerrRequests, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeerrRequestsRow{}
	for rows.Next() {
		var i ListSeerrRequestsRow
		if err := rows.Scan(
			&i.LinkID,
			&i.RequestID,
			&i.MediaType,
			&i.TmdbID,
			&i.TvdbID,
			&i.Title,
			&i.RequestStatus,
			&i.MediaStatus,
			&i.Is4k,
			&i.RequestedBy,
			&i.Seasons,
			&i.SeerrServerID,
			&i.InstanceID,
			&i.EntityID,
			&i.RequestedAt,
			&i.LastSnatchedAt,
			&i.LastSeenAt,
			&i.UpdatedAt,
			&i.LinkName,
			&i.InstanceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSeerrRequestsSnatched = `-- name: MarkSeerrRequestsSnatched :execrows
UPDATE seerr_requests
SET last_snatched_at = $2, updated_at = $2
WHERE instance_id = $1 AND entity_id = ANY($3::bigint[])
`

type MarkSeerrRequestsSnatchedParams struct {
	InstanceID     *uuid.UUID
	LastSnatchedAt *time.Time
	EntityIds      []int64
}

func (q *Queries) MarkSeerrRequestsSnatched(ctx context.Context, arg MarkSeerrRequestsSnatchedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSeerrRequestsSnatched, arg.InstanceID, arg.LastSnatchedAt, arg.EntityIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const priorityEntityIDs = `-- name: PriorityEntityIDs :many
SELECT DISTINCT entity_id::bigint AS entity_id
FROM seerr_requests
WHERE instance_id = $1 AND entity_id IS NOT NULL
`

func (q *Queries) PriorityEntityIDs(ctx context.Context, instanceID *uuid.UUID) ([]int64, error) {
	rows, err := q.db.Query(ctx, priorityEntityIDs, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var entity_id int64
		if err := rows.Scan(&entity_id); err != nil {
			return nil, err
		}
		items = append(items, entity_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSeerrCheck = `-- name: RecordSeerrCheck :exec
UPDATE seerr_links
SET last_seen_version = $2, last_check_at = $3, last_error = $4, updated_at = $3
WHERE id = $1
`

type RecordSeerrCheckParams struct {
	ID              uuid.UUID
	LastSeenVersion *string
	LastCheckAt     *time.Time
	LastError       *string
}

func (q *Queries) RecordSeerrCheck(ctx context.Context, arg RecordSeerrCheckParams) error {
	_, err := q.db.Exec(ctx, recordSeerrCheck,
		arg.ID,
		arg.LastSeenVersion,
		arg.LastCheckAt,
		arg.LastError,
	)
	return err
}

const recordSeerrSync = `-- name: RecordSeerrSync :exec
UPDATE seerr_links SET last_sync_at = $2, last_error = $3, updated_at = $2 WHERE id = $1
`

type RecordSeerrSyncParams struct {
	ID         uuid.UUID
	LastSyncAt *time.Time
	LastError  *string
}

func (q *Queries) RecordSeerrSync(ctx context.Context, arg RecordSeerrSyncParams) error {
	_, err := q.db.Exec(ctx, recordSeerrSync, arg.ID, arg.LastSyncAt, arg.LastError)
	return err
}

const updateSeerrLink = `-- name: UpdateSeerrLink :one
UPDATE seerr_links
SET name = $2, base_url = $3, api_key_enc = $4, enabled = $5, sonarr_instance_id = $6, radarr_instance_id = $7, updated_at = $8
WHERE id = $1
RETURNING id, name, base_url, api_key_enc, enabled, sonarr_instance_id, radarr_instance_id, last_seen_version, last_check_at, last_error, last_sync_at, created_at, updated_at
`

type UpdateSeerrLinkParams struct {
	ID               uuid.UUID
	Name             string
	BaseUrl          string
	ApiKeyEnc        []byte
	Enabled          bool
	SonarrInstanceID *uuid.UUID
	RadarrInstanceID *uuid.UUID
	UpdatedAt        time.Time
}

func (q *Queries) UpdateSeerrLink(ctx context.Context, arg UpdateSeerrLinkParams) (SeerrLink, error) {
	row := q.db.QueryRow(ctx, updateSeerrLink,
		arg.ID,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKeyEnc,
		arg.Enabled,
		arg.SonarrInstanceID,
		arg.RadarrInstanceID,
		arg.UpdatedAt,
	)
	var i SeerrLink
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyEnc,
		&i.Enabled,
		&i.SonarrInstanceID,
		&i.RadarrInstanceID,
		&i.LastSeenVersion,
		&i.LastCheckAt,
		&i.LastError,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSeerrRequest = `-- name: UpsertSeerrRequest :exec
INSERT INTO seerr_requests (
    link_id, request_id, media_type, tmdb_id, tvdb_id, title, request_status, media_status, is_4k,
    requested_by, seasons, seerr_server_id, instance_id, entity_id, requested_at, last_seen_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15, $16, $16
)
ON CONFLICT (link_id, request_id) DO UPDATE SET
    media_type = EXCLUDED.media_type, tmdb_id = EXCLUDED.tmdb_id, tvdb_id = EXCLUDED.tvdb_id,
    title = CASE WHEN EXCLUDED.title = '' THEN seerr_requests.title ELSE EXCLUDED.title END,
    request_status = EXCLUDED.request_status, media_status = EXCLUDED.media_status, is_4k = EXCLUDED.is_4k,
    requested_by = EXCLUDED.requested_by, seasons = EXCLUDED.seasons, seerr_server_id = EXCLUDED.seerr_server_id,
    instance_id = EXCLUDED.instance_id, entity_id = EXCLUDED.entity_id, requested_at = EXCLUDED.requested_at,
    last_seen_at = EXCLUDED.last_seen_at, updated_at = EXCLUDED.updated_at
`

type UpsertSeerrRequestParams struct {
	LinkID        uuid.UUID
	RequestID     int32
	MediaType     string
	TmdbID        int32
	TvdbID        int32
	Title         string
	RequestStatus int32
	MediaStatus   int32
	Is4k          bool
	RequestedBy   string
	Seasons       []int32
	SeerrServerID *int32
	InstanceID    *uuid.UUID
	EntityID      *int64
	RequestedAt   *time.Time
	LastSeenAt    time.Time
}

func (q *Queries) UpsertSeerrRequest(ctx context.Context, arg UpsertSeerrRequestParams) error {
	_, err := q.db.Exec(ctx, upsertSeerrRequest,
		arg.LinkID,
		arg.RequestID,
		arg.MediaType,
		arg.TmdbID,
		arg.TvdbID,
		arg.Title,
		arg.RequestStatus,
		arg.MediaStatus,
		arg.Is4k,
		arg.RequestedBy,
		arg.Seasons,
		arg.SeerrServerID,
		arg.InstanceID,
		arg.EntityID,
		arg.RequestedAt,
		arg.LastSeenAt,
	)
	return err
}
