// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package sqlcgen

import (
	"context"
	"time"
)

const ensureSettings = `-- name: EnsureSettings :one
INSERT INTO settings (singleton, updated_at) VALUES (TRUE, $1)
ON CONFLICT (singleton) DO UPDATE SET singleton = TRUE
RETURNING singleton, history_retention_days, user_agent, updated_at
`

func (q *Queries) EnsureSettings(ctx context.Context, updatedAt time.Time) (Setting, error) {
	row := q.db.QueryRow(ctx, ensureSettings, updatedAt)
	var i Setting
	err := row.Scan(
		&i.Singleton,
		&i.HistoryRetentionDays,
		&i.UserAgent,
		&i.UpdatedAt,
	)
	return i, err
}

const getSettings = `-- name: GetSettings :one

SELECT singleton, history_retention_days, user_agent, updated_at FROM settings WHERE singleton
`

// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
// SPDX-License-Identifier: EUPL-1.2
func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.Singleton,
		&i.HistoryRetentionDays,
		&i.UserAgent,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE settings
SET history_retention_days = $1, user_agent = $2, updated_at = $3
WHERE singleton
RETURNING singleton, history_retention_days, user_agent, updated_at
`

type UpdateSettingsParams struct {
	HistoryRetentionDays int32
	UserAgent            string
	UpdatedAt            time.Time
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (Setting, error) {
	row := q.db.QueryRow(ctx, updateSettings, arg.HistoryRetentionDays, arg.UserAgent, arg.UpdatedAt)
	var i Setting
	err := row.Scan(
		&i.Singleton,
		&i.HistoryRetentionDays,
		&i.UserAgent,
		&i.UpdatedAt,
	)
	return i, err
}
