// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
//
// SPDX-License-Identifier: EUPL-1.2

// Emits src/lib/theme.css from sveltesentio's oklch tokens and the dashboard preset, so
// the stylesheet is static (CSP hash mode, no runtime {@html}).
import { writeFileSync } from 'node:fs';
import { presetCss, presetDashboard } from '@sveltesentio/ui/presets';
import { themeCss } from '@sveltesentio/ui/tokens';

const banner = `/* SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me> */\n/* SPDX-License-Identifier: EUPL-1.2 */\n/* Generated by scripts/gen-theme.ts - do not edit. */\n`;
const css = `${banner}${themeCss()}\n${presetCss(presetDashboard, ':root')}\n`;
writeFileSync(new URL('../src/lib/theme.css', import.meta.url), css);
console.warn('wrote src/lib/theme.css');
