{{- if .Values.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "snatcharr.fullname" . }}
  labels:
    {{- include "snatcharr.labels" . | nindent 4 }}
  {{- with .Values.api.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.api.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.api.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.api.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "snatcharr.apiServiceName" $ }}
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
